Update "name" property of Higuera-Cary pusher
ComputationalRadiationPhysics/picongpu pull request #3371
Opened 2020-09-29 07:56 UTC by steindev

The name update ensures conformity with the openPMD standard.

2020-09-29 08:31 UTC, sbastrakov approved these changes

2020-09-29 08:36 UTC, sbastrakov requested changes
Wait, but this seems not compliant actually. Let's wait for Axel's reply in that topic.

2020-09-29 11:52 UTC, steindev commented
> Wait, but this seems not compliant actually. Let's wait for Axel's reply in that topic.

Well, as it is his advice and he mentioned that they do it elsewhere too, I expect it to be an accepted policy. Although it is not written explicitly in the standard that it is allowed to supplement the allowed value by more text, it does not seem explicitly forbidden, too. The policy suggested is a very convenient way until the standard includes the `particlePushParameters` attribute or allows for `particlePush:Higuera-Cary`.

In any case, the way we do it now is wrong. The policy suggested *may* be wrong, too, but is at least closer to the standard. If it is wrong, there is currently no standard conform way to do it. An update of the standard itself may take months. So I don't see any other way to do it *now*. Do you?

2020-09-29 12:55 UTC, sbastrakov commented
I agree it's a reasonable policy and the new value feels better than the old. However, from how I understood the standard (and that's why I would like to wait for an "official" response) it is equally non-conforming as the old value. And the conformant way is to just put `other`. So I agree your fix improves the situation, but I think putting `other` would be even better.

2020-10-01 09:49 UTC, PrometheusPi commented
I agree with @sbastrakov - we should wait for the official decision.

2020-10-02 07:48 UTC, steindev commented
But writing just `other` is in my opinion the worst solution of all, as it does not document at all what pusher is used.

2020-10-02 07:51 UTC, sbastrakov commented
It would be openPMD-conformant (as I believe we want and maybe even claim to be). And we can always add another output attribute, not governed by the standard, to add additional info.

2020-10-02 07:52 UTC, sbastrakov commented
Btw can even be `particlePushParameters` that you suggested to be added to the standard. and is generally logical with the naming schema being used.

2020-10-02 08:57 UTC, PrometheusPi commented
@steindev I personally agree with you that a more detailed description would be better for documentation, but the standard is very clear on that:
```
particlePush

    type: (string)
    scope: required
    description: Particle-Pushing Algorithm
    allowed values:
        - Boris (J.P. Boris. Relativistic plasma simulation-optimization of a hybrid code. USA, 1970)
        - Vay (doi:10.1063/1.2837054)
        - free-streaming (constantly moving with initial momentum)
        - LLRK4 (reduced Laundau-Lifshitz pusher via RK4 and classical radiation reaction, doi:10.1016/j.cpc.2016.04.002)
        - none (static particles such as probes)
        - other
```
There are no other values allowed - thus not even an extension on the given name `other`. I am not aware of any post processing code that currently relies on that attribute, but if there is one, it might break when adding non-standar entries. Perhaps, we should not only push the standard to add the `Higuera-Cary` pusher, but to allow for a string after `other`.

2020-10-02 08:58 UTC, PrometheusPi commented
@steindev Sorry - that already what you suggested in openPMD/openPMD-standard#225.

2020-10-02 09:00 UTC, steindev commented
> And we can always add another output attribute, not governed by the standard, to add additional info
> Btw can even be `particlePushParameters` ...

Ahh, then let's do it this way. But somebody probably needs implement that it is written to the file.

2020-10-02 09:14 UTC, PrometheusPi commented
@ax3l Just stated that no tool etc. will break if we use `other: Higuera-Cary`. So let's implement this. I will do this now.

2020-10-02 10:46 UTC, PrometheusPi approved these changes

2020-10-02 10:46 UTC, PrometheusPi commented
@sbastrakov Are you still against it?

2020-10-02 10:51 UTC, sbastrakov approved these changes
I still find it illogical, as instead of adhering to the standard we rely on the workaround that all the tools would accept the non-standard version. But it is not a big deal

2020-10-02 10:51 UTC, merged