Fix Ionization Current
ComputationalRadiationPhysics/picongpu pull request #3398
Opened 2020-10-20 11:23 UTC by jtrojok

There was an issue with the ionization current where there was a division by zero. When the electric field was zero (such as before a laser pulse), the ionization current was still called with ionization energy being zero. I fixed with an if-else-statement as you can see in the IonizationCurrent.hpp. The ionization current is now working (tested).

2020-10-20 11:48 UTC, sbastrakov reviewed
Thanks for the fix.

Just a small question / note. From the changed piece of code it is not obvious (to non-experts) that zero is not a legal value. Perhaps this kind of a check can be moved to somewhere where it's more obvious? I am not sure if this is possible to implement, just to float an idea

2020-10-20 14:06 UTC, jtrojok commented
I could also implement the fix in the JIonizationCalc.hpp. It would then return 0 when the ionization energy is zero. But I'd rather let it be the way it is now, because it is way faster right now than it would be if I implemented it in the JIonizationCalc.hpp. Right now nothing happens if the ionization energy is zero, but if I changed it, the assignment would assign a null current. I'd just add an explanatory comment.

2020-10-21 07:46 UTC, psychocoderHPC requested changes

2020-10-21 07:46 UTC, psychocoderHPC commented on include/picongpu/particles/ionization/byField/IonizationCurrent/IonizationCurrent.hpp
> +            if(retValue.ionizationEnergy == 0)
Could you please write `if(retValue.ionizationEnergy != 0.0_X)`. This will avoid the empty body.

2020-10-21 07:56 UTC, psychocoderHPC commented
> Thanks for the fix.
> 
> Just a small question / note. From the changed piece of code it is not obvious (to non-experts) that zero is not a legal value (as this piece does not have division). Perhaps this kind of a check can be moved to somewhere where it's more obvious, that is where the division actually happens? I am not sure if this is possible to implement, just to float an idea. If this is too hard or causes code duplication or there is some other limitation, it is fine to leave this logic as is, just perhaps document it in the comment.

I agree with @sbastrakov. IMO this fix needs at least a comment above the if and the implementation f `JIonizationCalc` needs also a comment above the `operator()`

2020-10-23 14:46 UTC, jtrojok commented
Added two comments as requested

2020-10-26 10:34 UTC, sbastrakov approved these changes

2020-10-26 17:43 UTC, PrometheusPi approved these changes

2020-11-02 11:21 UTC, merged