Use openPMD::getVersion() function
ComputationalRadiationPhysics/picongpu pull request #3427
Opened 2020-11-11 14:13 UTC by franzpoeschel

The `openPMD API` has a `std::string getVersion()` since `0.12.0`, so we don't need to construct the version string manually any longer.

2020-11-11 14:22 UTC, sbastrakov approved these changes

2020-11-11 16:45 UTC, PrometheusPi reviewed
looks good to me - still the compile suite throws an error

2020-11-11 16:46 UTC, PrometheusPi approved these changes
sorry - wanted to press "approve"

2020-11-11 16:55 UTC, PrometheusPi requested changes
The old openPMD stringstream interface is still used in https://github.com/franzpoeschel/picongpu/blob/e43f9fa9fd90830ffff62bfbfdfd0e95f2eb112b/include/picongpu/versionFormat.cpp#L196

2020-11-12 09:36 UTC, franzpoeschel commented
Argh, I built the wrong branch in my own test. Lemme fix..

2020-11-12 12:07 UTC, PrometheusPi approved these changes
@franzpoeschel Thanks for quickly fixing it.

2020-11-16 08:07 UTC, psychocoderHPC approved these changes

2020-11-16 08:07 UTC, merged