@psychocoderHPC CI: add HIP tests
ComputationalRadiationPhysics/picongpu pull request #3510
Opened 2021-01-28 19:55 UTC by psychocoderHPC

- add hipcc image definition
- activate tests for hip
- `n_wise_generator.py`:
  - fix issue that `clang++` was not detected

PR include #3509

2021-02-01 17:52 UTC, PrometheusPi approved these changes

2021-03-03 08:11 UTC, psychocoderHPC commented
ready for review

2021-03-03 13:27 UTC, sbastrakov requested changes
Looks good to me, just 2 small text suggestions.

2021-03-03 13:27 UTC, sbastrakov commented on share/ci/n_wise_generator.py
> +        # clang_cuda images can currenlty not be used because
Typo: should be `currently`

2021-03-03 13:27 UTC, sbastrakov commented on share/ci/n_wise_generator.py
> +        # the base image is hard coding -DALPAKA_CUDA_COMPILER=clang
Do you mean `hard setting` ?

2021-03-04 09:03 UTC, psychocoderHPC commented on share/ci/n_wise_generator.py
> +        # the base image is hard coding -DALPAKA_CUDA_COMPILER=clang
will change it to `... is setting ...`

2021-03-04 10:00 UTC, psychocoderHPC commented
Simeon provided the ROCm 4.0 container, therefore I will close this PR in favor of #3538. The new ROCm container also solved the runtime issue I observed on the AMD CI nodes.

@sbastrakov Your suggestions are included in #3538

2021-03-04 10:00 UTC, closed without merging