Fix some outdated docs relargind output and checkpoint backends
ComputationalRadiationPhysics/picongpu pull request #3535
Opened 2021-02-24 13:27 UTC by sbastrakov

This was noticed during a mattermost discussion on checkpoints.

2021-02-24 13:33 UTC, psychocoderHPC submitted a review, later dismissed

2021-02-24 13:56 UTC, sbastrakov commented
Sorry, found out a missing `not`, fixed and rebased.

2021-02-24 16:08 UTC, steindev requested changes
Nice catch! Few more spots to be corrected though.

And since you are editing the `TBG_macros.cfg` section of the documentation anyways: I suggest to add a comment to this cfg file, saying that this is really just a collection of snippets and not a working cfg file.
There is the
```bash
"$TBG_cfgPath"/submitAction.sh
```
missing at the end.
I actually stumbled upon this a few days ago, but @psychocoderHPC said it is just supposed to be a collection of snippets.
Although I think we might want to turn it into a full cfg by adding this line, since the file has the `.cfg` ending anyways and thus should be fully functional from my point of view.

2021-02-24 16:08 UTC, steindev commented on docs/source/usage/plugins/checkpoint.rst
>  Depending on the available external dependencies (see above), the options for the ``<IO-backend>`` are:
Would you be so kind and remove the double back ticks in line 54 as well?

2021-02-25 16:51 UTC, sbastrakov commented
Thanks @steindev , I've pushed another commit implementing your suggestion and one more thing I've noticed along the way.

2021-02-25 16:53 UTC, psychocoderHPC commented
> Nice catch! Few more spots to be corrected though.
> 
> And since you are editing the `TBG_macros.cfg` section of the documentation anyways: I suggest to add a comment to this cfg file, saying that this is really just a collection of snippets and not a working cfg file.
> There is the
> 
> ```shell
> "$TBG_cfgPath"/submitAction.sh
> ```
> 
> missing at the end.
> I actually stumbled upon this a few days ago, but @psychocoderHPC said it is just supposed to be a collection of snippets.
> Although I think we might want to turn it into a full cfg by adding this line, since the file has the `.cfg` ending anyways and thus should be fully functional from my point of view.

We can add it but IMO the file `TBG_macros.cfg` should be deleted and in the docu for each plugin there should a complete example with all options for each plugin that can be copy-pasted by the user.
The reason is that this will provide one point for the user to find all necessary information.

I am fine if you merge this PR first.

2021-03-01 10:40 UTC, steindev commented
@sbastrakov added the note to the `cfg`. Which, I think, is sufficient. I still like the idea to have this one place as an overview and example and get additional information via `picongpu --help`.

2021-03-01 10:41 UTC, steindev approved these changes

2021-03-01 10:41 UTC, merged