CMake: add option to enforce dependencies
ComputationalRadiationPhysics/picongpu pull request #3586
Opened 2021-04-14 16:04 UTC by psychocoderHPC

Allow to set cmake option `PIC_USE_<dependency>=ON` to enforce the usage
of a dependency.

fix #3473: use new option to avoid that CI is not compiling without
optional dependencies.

This PR is inspired by openMPD-api but the implementation is different.

# TODO

- [ ] add documentation to the cmake methods

2021-04-15 06:32 UTC, psychocoderHPC commented
In the future we could extent the reporting e.g.:

```
Optional Dependencies:
  openPMD: ON
     path: /home/user/openPMD
    version: 0.11.2 
  ADIOS1: OFF
  Splash: OFF
  PNGwriter: ON
    path: /home/user/pngwriter
    version: 0.7.0
  ISAAC: OFF
```

2021-04-15 07:02 UTC, ax3l commented
Hey that looks familiar :D Good choice!

2021-04-16 06:31 UTC, psychocoderHPC commented
This PR found the first silent disabled third party component :rocket: : https://gitlab.com/hzdr/crp/picongpu/-/jobs/1183724338#L926

In the example `WarmCopper` in the file `cmakeFlags` we added a cmake command to disable ISAAC `.

2021-04-16 12:43 UTC, sbastrakov requested changes
Nice! Some small text fixes

2021-04-16 12:43 UTC, sbastrakov commented on include/picongpu/CMakeLists.txt
> +# Create an options to configure the usage of a dependency
`Create options`, please remove `an`.

2021-04-16 12:43 UTC, sbastrakov commented on include/picongpu/CMakeLists.txt
> +            # non of these should appear in cmake-gui, so make them internal
Typo: should be `none`

2021-04-16 12:43 UTC, sbastrakov commented on include/picongpu/CMakeLists.txt
> +            message(FATAL_ERROR "Optional dependency '${name}' not found but explicit requested with 'PIC_USE_${name}=ON'.")
Typo: should be `explicitly`

2021-04-16 12:43 UTC, sbastrakov commented on include/picongpu/CMakeLists.txt
> +            # allow to use externally installed nlohmann_json
I think `using` is better than `to use`

2021-04-16 12:43 UTC, sbastrakov commented on include/picongpu/CMakeLists.txt
> +PIC_dependency(ISAAC "Framework to insiute visualize PIConGPU during the execution." AUTO)
Did you mean `in-situ` ?

2021-04-16 12:49 UTC, psychocoderHPC commented on include/picongpu/CMakeLists.txt
> +PIC_dependency(ISAAC "Framework to insiute visualize PIConGPU during the execution." AUTO)
yes^^

2021-04-16 14:40 UTC, psychocoderHPC commented
Thanks for the review, I added the fixes and pushed it.

2021-04-16 15:21 UTC, sbastrakov approved these changes

2021-04-20 05:51 UTC, psychocoderHPC commented
CI now passed, feel free to merge.

2021-04-20 07:58 UTC, merged