SPEC bechmark: add new configurations
ComputationalRadiationPhysics/picongpu pull request #3597
Opened 2021-04-20 13:06 UTC by psychocoderHPC

Add two additional configurations to compile for
  - 32bit and TSC particle shape
  - 64bit and TSC particle shape

The default case will not compile for 64bit because of the limited shared memory.
At all the selection should help in the CAAR project to validate the performance of 32bit and 64bit runs.

2021-04-21 08:08 UTC, sbastrakov requested changes
Just a small fix needed.

2021-04-21 08:08 UTC, sbastrakov commented on share/picongpu/benchmarks/SPEC/include/picongpu/param/memory.param
> +        static constexpr uint32_t BYTES_EXCHANGE_Z = 8 * 1024 * 1024; // 6 MiB
Comment in this line was not updated

2021-04-21 09:06 UTC, sbastrakov approved these changes

2021-04-21 14:18 UTC, psychocoderHPC commented
CI passed

2021-04-21 14:21 UTC, merged

2021-04-30 07:21 UTC, PrometheusPi commented
@Anton-Le are you including this adjustment in your Juwels Booster 64bit runs?