Profile for spock at ORNL
ComputationalRadiationPhysics/picongpu pull request #3627
Opened 2021-05-26 10:18 UTC by steindev

To run on the caar partition.

2021-05-26 10:31 UTC, steindev commented
Not ready for merge yet. Just a few more minutes...

2021-05-27 10:33 UTC, psychocoderHPC requested changes

2021-05-27 15:04 UTC, steindev commented on etc/picongpu/spock-ornl/caar.tpl
> +# export OMP_NUM_THREADS=1
Oops, correct. :-)

2021-05-27 19:42 UTC, psychocoderHPC approved these changes

2021-05-27 19:42 UTC, merged

2021-05-27 21:11 UTC, ax3l commented
@steindev don't forget to link the profile in the docs: https://picongpu.readthedocs.io/en/latest/install/profile.html

2021-05-27 21:12 UTC, ax3l commented
Ours is currently at https://warpx.readthedocs.io/en/latest/install/hpc/spock.html, the `HIPCC_COMPILE_FLAGS_APPEND` env var is a good touch.