Ensure variances are >= 0
ComputationalRadiationPhysics/picongpu pull request #3660
Opened 2021-06-25 12:01 UTC by jkelling

In `Estimate.kernel`, if the temperature drops to zero (particles are initialized with zero momentum variance), floating point math makes the variances become small, but sometimes negative inaccurate output.

This patch adds a `max` in `Estimate.kernel` to keep the variances from becoming negative.

```diff
< PIConGPUVerbose PHYSICS(1) | 0 (0 %) supercells had local Debye length estimate not resolved by a single cell
< PIConGPUVerbose PHYSICS(1) | Estimated weighted average temperature -7.58771e-11 KeV and corresponding Debye length -nan m.
<    The grid has -nan cells per average Debye length
---
> PIConGPUVerbose PHYSICS(1) | 1536 (100 %) supercells had local Debye length estimate not resolved by a single cell
> PIConGPUVerbose PHYSICS(1) | Estimated weighted average temperature 0 KeV and corresponding Debye length 0 m.
>    The grid has 0 cells per average Debye length
```

Are there other places where variance are calculated which may deserve the same treatment?

2021-06-25 12:18 UTC, sbastrakov requested changes
Indeed, that is a thing I didn't think of when writing this code. Thanks for fixing! There is a formatting issue, please fix following [this](https://picongpu.readthedocs.io/en/latest/dev/styleguide.html?highlight=xargs#format-all-files).

I am not sure we calculate variances anywhere else

2021-06-25 12:24 UTC, jkelling commented
> Indeed, that is a thing I didn't think of when writing this code. Thanks for fixing! There is a formatting issue, please fix following [this](https://picongpu.readthedocs.io/en/latest/dev/styleguide.html?highlight=xargs#format-all-files).

Fixed.

2021-06-25 12:26 UTC, jkelling commented
I added another commit fixing the spelling of the prefix "kilo" (`K` -> `k`) in output and a comment. This does only occur in the `debyeLength` area, so I would like to bunch in with this PR and no open a new one.

2021-06-25 12:41 UTC, sbastrakov approved these changes
I think both `keV` and `KeV` are used, but don't mind your change.

2021-06-28 06:01 UTC, psychocoderHPC approved these changes

2021-06-28 06:01 UTC, merged