Isaac plugin vector field vis compatility and benchmarking
ComputationalRadiationPhysics/picongpu pull request #3719
Opened 2021-08-12 09:58 UTC by FelixTUD

- Added compatibility to the isaac vector field visualization and usage of vector field sources
- Benchmarking code example, can be enabled in .cfg files with the parameter `--isaac.timingsFilename [PATH/FILENAME.csv]`

Known issues:
- Moving window creates artefacts at front GPUs as the seeding positions for the vector field visualization are stationary

2021-08-13 07:02 UTC, psychocoderHPC commented
@FelixTUD I added the documentation for the new command-line option and updated the CI to pull the latest ISAAC dev.

@PrometheusPi Could you do a review, at least the commit with the documentation change.

2021-08-13 07:04 UTC, psychocoderHPC submitted a review, later dismissed

2021-08-13 14:25 UTC, PrometheusPi commented
@psychocoderHPC I will do ...

2021-08-13 14:36 UTC, PrometheusPi requested changes
A few typos. I provided a quick fix for all of them.

2021-08-13 14:36 UTC, PrometheusPi commented on docs/TBG_macros.cfg
> +#     --isaac.timingsFilename benchRsults.txt
```suggestion
#     --isaac.timingsFilename benchResults.txt
```

2021-08-13 14:36 UTC, PrometheusPi commented on docs/source/usage/plugins/isaac.rst
> +                                  to be changed for tunneling reasons or if more than one server shall run on
```suggestion
                                  The default value is ``2458`` (for the in-situ plugins), but may needs to
                                  be changed for tunneling reasons or if more than one server shall run on
```

2021-08-13 14:36 UTC, PrometheusPi commented on include/picongpu/param/isaac.param
> +         *  the join of Native_Seq and Density_Seq. */
```suggestion
         *  joining Native_Seq and Density_Seq. */
```

2021-08-13 14:36 UTC, PrometheusPi commented on share/ci/install/isaac.sh
> +# issac version with bew LIC kernel https://github.com/ComputationalRadiationPhysics/isaac/pull/143
```suggestion
# issac version with new LIC kernel https://github.com/ComputationalRadiationPhysics/isaac/pull/143
```

2021-08-13 14:36 UTC, PrometheusPi commented on share/picongpu/benchmarks/SPEC/include/picongpu/param/isaac.param
> +        //      deriveField::derivedAttributes::Density, filter::All>;
Is this comnented code OK?

2021-08-13 14:36 UTC, PrometheusPi commented on share/picongpu/benchmarks/SPEC/include/picongpu/param/isaac.param
> +         *  the join of Native_Seq and Density_Seq. */
```suggestion
         *  joining Native_Seq and Density_Seq. */
```

2021-08-13 14:36 UTC, PrometheusPi commented on share/picongpu/tests/compileCurrentSolver/include/picongpu/param/isaac.param
> +         *  the join of Native_Seq and Density_Seq. */
```suggestion
         *  joining Native_Seq and Density_Seq. */
```

2021-08-13 14:36 UTC, PrometheusPi commented on share/picongpu/tests/compileFieldSolver/include/picongpu/param/isaac.param
> +         *  the join of Native_Seq and Density_Seq. */
```suggestion
         *  joining Native_Seq and Density_Seq. */
```

2021-08-13 14:36 UTC, PrometheusPi commented on share/picongpu/tests/compileParticlePusher/include/picongpu/param/isaac.param
> +         *  the join of Native_Seq and Density_Seq. */
```suggestion
         *  joining Native_Seq and Density_Seq. */
```

2021-08-21 05:05 UTC, PrometheusPi commented
As discussed, text changes will be added in a separate pull request to not delay merging.

2021-08-21 05:06 UTC, PrometheusPi approved these changes

2021-08-21 05:06 UTC, merged