Read IO plugin configuration (openPMD plugin) from reading applications (TOML)
ComputationalRadiationPhysics/picongpu pull request #3720
Opened 2021-08-12 14:33 UTC by franzpoeschel

Close #3717, see there for a detailed description

TODO:

- [ ] Add thirdparty library and integrate it with the build system
- [ ] Implement new logic in openPMD plugin
- [ ] Actually read config from TOML files (currently, a little example is hardcoded)
- [ ] Check that `selfRegister==true` is handled correctly (checkpoint writing)
- [ ] Discuss command line parameter schema (may drop the `--openPMD.period dynamic` thing, it's easy to implement for now)

2021-08-12 19:25 UTC, franzpoeschel commented on include/picongpu/plugins/openPMD/toml.cpp
> +            return {result.end(), result.end()};
Note to self: result.begin()

2021-08-13 13:37 UTC, franzpoeschel commented
Just did a little test run with this thing:

First TOML file:
```toml
[period]
200 = ["E", "B"]
400 = "fields_all"
```

Second one:
```toml
[period]
500 = "species_all"
```
Resulting dataset:
```
  float     /data/0/fields/B/x                                        {32, 32, 32}
  float     /data/0/fields/B/y                                        {32, 32, 32}
  float     /data/0/fields/B/z                                        {32, 32, 32}
  float     /data/0/fields/E/x                                        {32, 32, 32}
  float     /data/0/fields/E/y                                        {32, 32, 32}
  float     /data/0/fields/E/z                                        {32, 32, 32}
  float     /data/0/fields/e_all_chargeDensity                        {32, 32, 32}
  float     /data/0/fields/e_all_energyDensity                        {32, 32, 32}
  float     /data/0/fields/e_all_particleMomentumComponent            {32, 32, 32}
  float     /data/0/fields/i_all_chargeDensity                        {32, 32, 32}
  float     /data/0/fields/i_all_energyDensity                        {32, 32, 32}
  float     /data/0/fields/i_all_particleMomentumComponent            {32, 32, 32}
  uint64_t  /data/0/fields/picongpu_idProvider/nextId                 {1, 1, 1}
  uint64_t  /data/0/fields/picongpu_idProvider/startId                {1, 1, 1}
  float     /data/0/particles/e/momentum/x                            {819200}
  float     /data/0/particles/e/momentum/y                            {819200}
  float     /data/0/particles/e/momentum/z                            {819200}
  uint64_t  /data/0/particles/e/particlePatches/extent/x              {1}
  uint64_t  /data/0/particles/e/particlePatches/extent/y              {1}
  uint64_t  /data/0/particles/e/particlePatches/extent/z              {1}
  uint64_t  /data/0/particles/e/particlePatches/numParticles          {1}
  uint64_t  /data/0/particles/e/particlePatches/numParticlesOffset    {1}
  uint64_t  /data/0/particles/e/particlePatches/offset/x              {1}
  uint64_t  /data/0/particles/e/particlePatches/offset/y              {1}
  uint64_t  /data/0/particles/e/particlePatches/offset/z              {1}
  float     /data/0/particles/e/position/x                            {819200}
  float     /data/0/particles/e/position/y                            {819200}
  float     /data/0/particles/e/position/z                            {819200}
  int32_t   /data/0/particles/e/positionOffset/x                      {819200}
  int32_t   /data/0/particles/e/positionOffset/y                      {819200}
  int32_t   /data/0/particles/e/positionOffset/z                      {819200}
  float     /data/0/particles/e/weighting                             {819200}
  float     /data/0/particles/i/momentum/x                            {819200}
  float     /data/0/particles/i/momentum/y                            {819200}
  float     /data/0/particles/i/momentum/z                            {819200}
  uint64_t  /data/0/particles/i/particlePatches/extent/x              {1}
  uint64_t  /data/0/particles/i/particlePatches/extent/y              {1}
  uint64_t  /data/0/particles/i/particlePatches/extent/z              {1}
  uint64_t  /data/0/particles/i/particlePatches/numParticles          {1}
  uint64_t  /data/0/particles/i/particlePatches/numParticlesOffset    {1}
  uint64_t  /data/0/particles/i/particlePatches/offset/x              {1}
  uint64_t  /data/0/particles/i/particlePatches/offset/y              {1}
  uint64_t  /data/0/particles/i/particlePatches/offset/z              {1}
  float     /data/0/particles/i/position/x                            {819200}
  float     /data/0/particles/i/position/y                            {819200}
  float     /data/0/particles/i/position/z                            {819200}
  int32_t   /data/0/particles/i/positionOffset/x                      {819200}
  int32_t   /data/0/particles/i/positionOffset/y                      {819200}
  int32_t   /data/0/particles/i/positionOffset/z                      {819200}
  float     /data/0/particles/i/weighting                             {819200}
  float     /data/200/fields/B/x                                      {32, 32, 32}
  float     /data/200/fields/B/y                                      {32, 32, 32}
  float     /data/200/fields/B/z                                      {32, 32, 32}
  float     /data/200/fields/E/x                                      {32, 32, 32}
  float     /data/200/fields/E/y                                      {32, 32, 32}
  float     /data/200/fields/E/z                                      {32, 32, 32}
  uint64_t  /data/200/fields/picongpu_idProvider/nextId               {1, 1, 1}
  uint64_t  /data/200/fields/picongpu_idProvider/startId              {1, 1, 1}
  float     /data/400/fields/B/x                                      {32, 32, 32}
  float     /data/400/fields/B/y                                      {32, 32, 32}
  float     /data/400/fields/B/z                                      {32, 32, 32}
  float     /data/400/fields/E/x                                      {32, 32, 32}
  float     /data/400/fields/E/y                                      {32, 32, 32}
  float     /data/400/fields/E/z                                      {32, 32, 32}
  float     /data/400/fields/e_all_chargeDensity                      {32, 32, 32}
  float     /data/400/fields/e_all_energyDensity                      {32, 32, 32}
  float     /data/400/fields/e_all_particleMomentumComponent          {32, 32, 32}
  float     /data/400/fields/i_all_chargeDensity                      {32, 32, 32}
  float     /data/400/fields/i_all_energyDensity                      {32, 32, 32}
  float     /data/400/fields/i_all_particleMomentumComponent          {32, 32, 32}
  uint64_t  /data/400/fields/picongpu_idProvider/nextId               {1, 1, 1}
  uint64_t  /data/400/fields/picongpu_idProvider/startId              {1, 1, 1}
  uint64_t  /data/500/fields/picongpu_idProvider/nextId               {1, 1, 1}
  uint64_t  /data/500/fields/picongpu_idProvider/startId              {1, 1, 1}
  uint64_t  /data/500/particles/e/particlePatches/extent/x            {1}
  uint64_t  /data/500/particles/e/particlePatches/extent/y            {1}
  uint64_t  /data/500/particles/e/particlePatches/extent/z            {1}
  uint64_t  /data/500/particles/e/particlePatches/numParticles        {1}
  uint64_t  /data/500/particles/e/particlePatches/numParticlesOffset  {1}
  uint64_t  /data/500/particles/e/particlePatches/offset/x            {1}
  uint64_t  /data/500/particles/e/particlePatches/offset/y            {1}
  uint64_t  /data/500/particles/e/particlePatches/offset/z            {1}
  uint64_t  /data/500/particles/i/particlePatches/extent/x            {1}
  uint64_t  /data/500/particles/i/particlePatches/extent/y            {1}
  uint64_t  /data/500/particles/i/particlePatches/extent/z            {1}
  uint64_t  /data/500/particles/i/particlePatches/numParticles        {1}
  uint64_t  /data/500/particles/i/particlePatches/numParticlesOffset  {1}
  uint64_t  /data/500/particles/i/particlePatches/offset/x            {1}
  uint64_t  /data/500/particles/i/particlePatches/offset/y            {1}
  uint64_t  /data/500/particles/i/particlePatches/offset/z            {1}
  float     /data/600/fields/B/x                                      {32, 32, 32}
  float     /data/600/fields/B/y                                      {32, 32, 32}
  float     /data/600/fields/B/z                                      {32, 32, 32}
  float     /data/600/fields/E/x                                      {32, 32, 32}
  float     /data/600/fields/E/y                                      {32, 32, 32}
  float     /data/600/fields/E/z                                      {32, 32, 32}
  uint64_t  /data/600/fields/picongpu_idProvider/nextId               {1, 1, 1}
  uint64_t  /data/600/fields/picongpu_idProvider/startId              {1, 1, 1}
```

2021-08-13 19:50 UTC, franzpoeschel commented on include/picongpu/plugins/openPMD/toml.cpp
> +                              .value;
remove leftover stuff

2021-08-13 19:50 UTC, franzpoeschel commented on include/picongpu/plugins/openPMD/toml.cpp
> +        DataSources::DataSources(std::string tomlFiles) : m_period{waitForParseAndMergeTomlFiles(tomlFiles, 5s)}
unneeded copy

2021-08-16 07:52 UTC, franzpoeschel commented on include/picongpu/plugins/openPMD/toml.cpp
> +                              .value;
eh, no removing
that one stays

2021-08-16 10:00 UTC, franzpoeschel commented
The latest commit fixes waiting for late files and adds logging for that:
```
PIConGPUVerbose INPUT_OUTPUT(32) | openPMD: Reading data requirements from TOML files:                                                                                               
        [/home/franzpoeschel/src/singularity/toml1.toml, /home/franzpoeschel/src/singularity/toml0.toml]                                                                            
PIConGPUVerbose INPUT_OUTPUT(32) | openPMD: Still waiting for TOML files:                                                                                                            
        [/home/franzpoeschel/src/singularity/toml0.toml]                                                                                                                            
PIConGPUVerbose INPUT_OUTPUT(32) | openPMD: Still waiting for TOML files:
        [/home/franzpoeschel/src/singularity/toml0.toml]
PIConGPUVerbose INPUT_OUTPUT(32) | openPMD: Still waiting for TOML files:
        [/home/franzpoeschel/src/singularity/toml0.toml]
PIConGPUVerbose INPUT_OUTPUT(32) | openPMD: opening Series openPMD/stream
PIConGPUVerbose INPUT_OUTPUT(32) | openPMD: open file: openPMD/stream.bp
```

Next up: parallel reading (i.e. non-parallel reading)

2021-08-16 11:59 UTC, franzpoeschel commented
(PR stalled for now until René is back from holiday to review this approach.)

2021-09-30 14:47 UTC, franzpoeschel commented
Discussed offline with René:
We will change this such that one instance of the openPMD plugin can be configured entirely by one single TOML file. This file will have sections for the single reading codes' data requirements:
```toml
[openPMD]
"file" = simOutput
"ext" = "bp"
"backendConfig" = "@./adios2_config.json"

[sink.analysis_code_name.period]
200 = ["E", "B"]
400 = "fields_all"

[sink.other_analysis_code_name.period]
500 = "species_all"
```

Under the `openPMD` group, we simply put all classical cmd line parameters of the openPMD plugin. Under `[sink.<arbitrary name>.period]`, the single reading codes' data requirements are found. This allows us to add other sink-specific keys in future:
```toml
# this will not be part of this PR
# just demonstrating that this schema is extensible
[sink.analysis_code_name]
"logging" = true
```

Other point discussed: Allow time slicing syntax

2021-10-19 10:30 UTC, franzpoeschel commented
Alright, command line parameter handling should now work. Still need to test that checkpoint/restarting is handled correctly, and I might need some help so that this PR does not also add a parameter `--checkpoint.openPMD.toml`. The plugin checks that `toml` is the only parameter specifies and fails if any other parameter has been passed.

2021-11-04 10:54 UTC, PrometheusPi commented
@franzpoeschel What is the status of this pul request?

2021-11-04 11:34 UTC, franzpoeschel commented
@PrometheusPi I meet with René next week to discuss the current status. If we agree that the approach taken by this is ok, I expect it can be merged soon.

Note that this PR is **not** about TOML configuration for the openPMD-api, but for PIConGPU's openPMD plugin.

2021-11-10 15:27 UTC, franzpoeschel commented
I added the things we talked about yesterday @psychocoderHPC:
- [ ] Allow to call the openPMD plugin with `--openPMD.toml "" --openPMD.file output --openPMD.period 100`, e.g. consider empty strings as equivalent to no passed parameters
  I'd generally appreciate if someone who uses the openPMD plugin as a multi plugin could check if things are still running.
- [ ] Added documentation. I've documented most of it with inline comments inside a [sample `.toml` file](https://github.com/ComputationalRadiationPhysics/picongpu/blob/2a358739be22d271e41c2d681fa55eceae0e4a86/docs/source/usage/plugins/openPMD.toml)
- [ ] Make the `toml::DataSources` stateless

2021-11-25 08:28 UTC, psychocoderHPC commented
I tested that multi-plugin usage with command line parameters still works.
We need to rebase this PR after #3919 is merged because of conflicts in the documentation.

2021-11-25 08:29 UTC, psychocoderHPC requested changes

2021-11-25 08:29 UTC, psychocoderHPC commented on include/picongpu/plugins/common/MPIHelpers.hpp
> +#include <vector>
`#include <string>` is missing

2021-11-26 12:20 UTC, psychocoderHPC commented
PR can be rebased

2021-11-26 12:36 UTC, franzpoeschel commented
> PR can be rebased

done

2021-11-29 08:20 UTC, psychocoderHPC commented
@franzpoeschel What do you mean by `Timeout for waiting on files?`

2021-11-29 10:06 UTC, franzpoeschel commented
> @franzpoeschel What do you mean by `Timeout for waiting on files?`

In our intended workflows, the TOML file is created asynchronously by the reading codes. So, as long as the file is not there yet, [these lines here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/c4a367f7222ad658fafa854e78eb332862fdb559/include/picongpu/plugins/openPMD/toml.cpp#L232) will sleep until the file is found. Should I keep that part? If yes, I think I should add a timeout. @psychocoderHPC

2021-11-29 11:27 UTC, psychocoderHPC commented
> > @franzpoeschel What do you mean by `Timeout for waiting on files?`
> 
> In our intended workflows, the TOML file is created asynchronously by the reading codes. So, as long as the file is not there yet, [these lines here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/c4a367f7222ad658fafa854e78eb332862fdb559/include/picongpu/plugins/openPMD/toml.cpp#L232) will sleep until the file is found. Should I keep that part? If yes, I think I should add a timeout. @psychocoderHPC

Ohh yes, a timeout makes sense. IMO set as default 5min.

2021-11-29 12:55 UTC, franzpoeschel commented
> > > @franzpoeschel What do you mean by `Timeout for waiting on files?`
> > 
> > 
> > In our intended workflows, the TOML file is created asynchronously by the reading codes. So, as long as the file is not there yet, [these lines here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/c4a367f7222ad658fafa854e78eb332862fdb559/include/picongpu/plugins/openPMD/toml.cpp#L232) will sleep until the file is found. Should I keep that part? If yes, I think I should add a timeout. @psychocoderHPC
> 
> Ohh yes, a timeout makes sense. IMO set as default 5min.

Done and tested

2022-01-28 16:29 UTC, steindev approved these changes

2022-01-28 16:32 UTC, merged