fix rad restart
ComputationalRadiationPhysics/picongpu pull request #3961
Opened 2022-01-14 15:22 UTC by PrometheusPi

This pull request fixes the issue #3959.

- [ ] test that restarts work

The error was caused by the inconsistent naming of checkpoint file. In order to keep compatibility with the old python modules that were based on sequential libSplash output, files are still written with a `%T_0_0_0.h5` suffix. But the restart routine was looking for a more modern style `%T.h5`. The error was most likely introduced while refactoring the pull request #3566. 

Additionally, the radiation plugin defaults to not fail when not finding a restart file but to assume zeros. Since the warning is written to the PIConGPU IO log (by default not active)  instead to the radiation standard log (by default active) the warning was not prompted. 

Thus this pull request:
 - fixes file naming
 - switches log level 
 
 **For all those effected (e.g. @Anton-Le):**
 You can restart by changing the naming from `*%T_0_0_0.h5` to `*%T.h5`.
  
For data analysis, the loading of the restart files from PIConGPU is not needed. You just need to load them manually and add them accordingly. (Please be aware that any non-complex output like totalRad (or lastRad) are still wrong - but with using the openPMD output, there should be no problem if your simulation did not restart from the radiation checkpoint. - That's why PIConGPU does  not fail when it does not find a radiation restart file.)

2022-01-14 22:04 UTC, Anton-Le commented
Great.

I'll try it out as soon as the system permits!

2022-01-18 16:15 UTC, sbastrakov requested changes
There is a problem with clang formatting, as pointed out by CI. Please format using [these instructions](https://picongpu.readthedocs.io/en/latest/dev/styleguide.html)

2022-01-18 16:22 UTC, PrometheusPi commented
@sbastrakov Thanks for pointing out the CI issue - I did see it since I was occupied with testing this PR on taurus. I will fix it asap.

2022-01-20 17:10 UTC, PrometheusPi commented
I tested the restart on taurus and it works. 
![grafik](https://user-images.githubusercontent.com/5121158/150387427-fa2f0b93-e1d4-4e0a-ac81-33fb50df9f41.png)

What I do not understand is, why the energy value between the previous test (on hemera) and this on (on taurus) differ that much. Previously it was 100fJ here it's 10^-30J. Perhaps I made a error in my previous analysis - which I can not validate as long as hemera is down. 

However, the restart works as expected.

2022-01-20 17:11 UTC, PrometheusPi commented
Could be merged from my side.

2022-01-20 17:47 UTC, sbastrakov approved these changes

2022-01-24 07:42 UTC, psychocoderHPC approved these changes

2022-01-24 07:43 UTC, merged