Expand documentation on running interactively
ComputationalRadiationPhysics/picongpu pull request #3967
Opened 2022-01-25 16:57 UTC by steindev

Adds a profile for system 'bash' and adds a paragraph in docs on how to run interactively using TBG.
Hopefully this helps new users to follow our introduction on their local workstation or laptop and decreases the effort to 'just  try' PIConGPU.

To be in line with this thought, the value of `PIC_BACKEND="omp2b:native"` in the profile is chosen on purpose to allow compilation and running on standard hardware.
I am not sure whether the 'native' in this definition is actually required or may not be required but rather a 'fail-safe' setting.
Please comment and I will change if necessary.

2022-01-31 09:54 UTC, PrometheusPi requested changes
just a minor typo that needs to be fixed

2022-01-31 09:54 UTC, PrometheusPi commented on docs/source/install/profile.rst
> +If there is no profile for the HPC system you are wroking on available, feel free to create one and
```suggestion
If no profile is available for the HPC system you are working on, feel free to create one and
```

2022-01-31 10:29 UTC, pordyna commented
Maybe we should also mention that our `.profile` files usually have the `getNode` and `getDevice` functions. So that  on hemera, it  is possible to use the standard profiles to run interactively on any of the gpu queues with the combination of `getDevice` and `-s bash` in `tbg`.

2022-01-31 14:02 UTC, steindev commented
Thanks @PrometheusPi and @pordyna. I updated the text.

2022-01-31 14:56 UTC, PrometheusPi approved these changes

2022-02-02 15:38 UTC, sbastrakov approved these changes

2022-02-02 15:39 UTC, merged