remove obsolete check in tpl
ComputationalRadiationPhysics/picongpu pull request #3987
Opened 2022-02-15 11:08 UTC by PrometheusPi

@steindev and I wondered why restarting simulation on crusher never ran but always "crashed". The reason for this error originates from a obsolete check that should only run PIConGPU if `cuda_memtest` ran successfully. 
However, since on AMD GPUs, there is no `cuda_memtest`. The check thus validates the return value of the previous command: creating the symbolic link between `output` and `stderr`, which of course fails if the link already exists. Thus PIConGPU never ran when the link already existed. 
This pull request fixes this issue by removing the check completely.

2022-02-15 12:11 UTC, PrometheusPi commented
Added spock `*.tpl` as well since it had the same error.

2022-02-17 13:06 UTC, sbastrakov reviewed
This change seems valid, but to have been done on top of another branch, not on clean `dev`.

2022-02-25 13:25 UTC, steindev commented
As @sbastrakov pointed out, the first commit in this PR seems to be related to ISAAC, and not to this PR. I suggest to remove this first commit while squashing the others and updating the commit comment to be more verbose, like 'remove obsolete check for successful cuda memcheck on spock and crusher'.

2022-02-25 13:26 UTC, steindev requested changes
As @sbastrakov pointed out, the first commit in this PR seems to be related to ISAAC, and not to this PR. I suggest to remove this first commit while squashing the others and updating the commit comment to be more verbose, like 'remove obsolete check for successful cuda memcheck on spock and crusher'.

2022-02-28 12:30 UTC, PrometheusPi commented
Sorry guys (@sbastrakov and @steindev) - will fix this now.

2022-02-28 12:45 UTC, psychocoderHPC submitted a review, later dismissed

2022-03-01 10:05 UTC, steindev approved these changes

2022-03-01 10:05 UTC, merged