Add utilities for calculating incident B from E using plane wave approximation
ComputationalRadiationPhysics/picongpu pull request #4050
Opened 2022-04-08 16:56 UTC by sbastrakov

We will need them for implementing laser profiles, and they also make sense for the `Free` profile as default mode.

2022-04-11 09:56 UTC, psychocoderHPC requested changes

2022-04-11 09:56 UTC, psychocoderHPC commented on include/picongpu/fields/incidentField/profiles/Free.def
> +                template<typename T_FunctorIncidentE, typename T_FunctorIncidentB = DefaultFunctorIncidentB>
Please rename `DefaultFunctorIncidentB` into a name that points to the used method to derive the field from E.

2022-04-11 11:40 UTC, sbastrakov commented on include/picongpu/fields/incidentField/profiles/Free.def
> +                template<typename T_FunctorIncidentE, typename T_FunctorIncidentB = DefaultFunctorIncidentB>
Done

2022-04-12 07:01 UTC, sbastrakov commented
@psychocoderHPC your suggestion is implemented and tests passed, ready for re-review.

2022-04-13 08:38 UTC, psychocoderHPC approved these changes

2022-04-13 08:38 UTC, merged