Remove zlib from required dependencies in the docs
ComputationalRadiationPhysics/picongpu pull request #4128
Opened 2022-05-25 15:15 UTC by sbastrakov

It is no longer required directly by PIConGPU and so the docs were outdated. Also update all the profiles to no longer use it.

Fixes #4125

2022-05-26 09:34 UTC, Anton-Le commented
Correct me if I'm wrong, but to my knowledge ADIOS2 (and HDF5?) require zlib as a dependency. So while it's not a direct dependency it is one that would be required for the library stack and the appropriate modules should not be removed from the profiles.

2022-05-30 07:05 UTC, sbastrakov commented
I think ADIOS2 doesn't require it.
However, regardless of that even ADIOS2 and HDF5 are *not* our dependencies. openPMD API is. So i think we should only mark that and refer to its installation settings, otherwise our instructions would constantly get outdated anyways with changed to openPMD API. @psychocoderHPC what do you think?

2022-05-30 11:40 UTC, psychocoderHPC commented
I agree with @sbastrakov zlib is a requirement of HDF5 and can be a requirement of ADIOS2 but both are indirect dependencies coming from openPMD-api, therefore, there is no need for us to document these dependencies.

2022-05-30 11:41 UTC, sbastrakov commented
But continuing this logic, we should then also remove `HDF5` and `ADIOS2` as they are dependencies of `openPMD API` which is our direct dependency?

2022-05-30 11:45 UTC, psychocoderHPC requested changes
Could you please keep in all profiles zlib. It is a dependency of HDF5 and mostly not loaded automatically when HDF5 is loaded.

2022-05-30 11:45 UTC, psychocoderHPC commented on docs/source/install/profile.rst
> +For this profile to work, you need to download the :ref:`PIConGPU source code <install-dependencies-picongpu>` and install :ref:`boost, libpng, c-blosc, PNGwriter and ADIOS <install-dependencies>` ma
we should remove `c-blosc` here and instead of `ADIOS` write `ADIOS2`

2022-05-30 11:45 UTC, psychocoderHPC commented on etc/picongpu/aris-grnet/gpu_picongpu.profile.example
> -# module load zlib/1.2.8
could you please keep in all profiles `zlib` on most systems the module system is not correctly loading the dependencies of HDF5, therefore we should keep loading zlib in all profiles.

2022-05-30 11:49 UTC, psychocoderHPC commented
> But continuing this logic, we should then also remove `HDF5` and `ADIOS2` as they are dependencies of `openPMD API` which is our direct dependency?

I agree we should remove it because OpenPMD-api is documenting the dependencies well. We should check where the dependency tree png in the documentation is used and keep the full dependency graph or remove it, or update it and put PIConGPU onto the top.

2022-05-31 09:24 UTC, Anton-Le commented
The documentation for the installation of HDF5 and ADIOS2 should then be moved from the [PIConGPU docs](https://picongpu.readthedocs.io/en/latest/install/dependencies.html#hdf5)  to the [openPMD docs](https://openpmd-api.readthedocs.io/en/latest/dev/dependencies.html#development-dependencies), as there the dependencies are just listed, but without the helpful hints regarding compilation.

2022-05-31 09:29 UTC, sbastrakov commented
@Anton-Le I agree, and we even partially do it already in [this section](https://picongpu.readthedocs.io/en/latest/install/dependencies.html#openpmd-api). But we still have standalone sections for HDF5 and ADIOS2 anyways, which then should be removed as well.

2022-05-31 09:43 UTC, sbastrakov commented
@psychocoderHPC ready for re-review

2022-06-01 07:43 UTC, psychocoderHPC approved these changes

2022-06-01 07:43 UTC, merged

2022-06-01 07:44 UTC, sbastrakov commented
I will follow it up with removing ADIOS2 and HDF5 as direct dependencies, as discussed above