Update the JUWELS booster profile.
ComputationalRadiationPhysics/picongpu pull request #4130
Opened 2022-05-26 09:53 UTC by Anton-Le

This updates the JUWELS Booster profile for PIConGPU to reflect the software of the system in 2022.

2022-05-30 07:09 UTC, sbastrakov requested changes
The history of this PR has a few merge commits (e.g. it could be seen in github view of this PR - 7/8 commits are merges). Could you remove those e.g. by putting your last commit with "real" changes on top of the current dev?

2022-06-03 06:38 UTC, psychocoderHPC commented
I removed the merge commits. I assume @Anton-Le merged the dev into an old release and therefore the strange merge commits were shown. I built it all from scratch with the clean dev branch as a base and forced pushed to @Anton-Le branch.

2022-06-03 06:38 UTC, psychocoderHPC approved these changes

2022-06-03 07:54 UTC, sbastrakov approved these changes

2022-06-03 07:54 UTC, merged