fix typo
ComputationalRadiationPhysics/picongpu pull request #4346
Opened 2022-11-09 13:48 UTC by pordyna

Fix a typo in `particle.param`
This doesn't need the CI to run, @ComputationalRadiationPhysics/picongpu-maintainers can someone set a no-ci flag?

2022-11-09 13:51 UTC, PrometheusPi approved these changes, later dismissed

2022-11-09 14:07 UTC, BrianMarre commented
the CI pyflake is wrong,
it should be:
```
pyflakes $(ls -d */ | grep -Ev "thirdParty|test") $(find test/ | grep "\.py$" | grep -Ev "__init__.py|__main__.py")
```
but it is
```
 pyflakes $(ls -w 1 -d */ | grep -v thirdParty | tr "\n" " ")
```

2022-11-09 14:45 UTC, SimeonEhrig commented
@pordyna Your commit bases on a old state of the dev branch. For unclarified reasons GitHub does not recognize it.
I'm also not sure, if a automatic rebase is done for the CI. @psychocoderHPC Do you have a idea?

2022-11-09 14:58 UTC, psychocoderHPC commented
> @pordyna Your commit bases on a old state of the dev branch. For unclarified reasons GitHub does not recognize it. I'm also not sure, if a automatic rebase is done for the CI. @psychocoderHPC Do you have a idea?

In that case Github was able to merge all changes therefore you do not see an error.

@pordyna please rebase your branch to the latest dev branch.

2022-11-09 15:05 UTC, psychocoderHPC requested changes

2022-11-09 15:05 UTC, psychocoderHPC commented on include/picongpu/param/particle.param
> + * can be used in speciesInitialization.param for particle species
please fix this in all `particle.pram` files in the code base

2022-11-09 15:32 UTC, PrometheusPi commented
Thanks for rebasing @pordyna

2022-11-14 10:52 UTC, pordyna commented
@psychocoderHPC I changed other files

2022-11-14 11:58 UTC, PrometheusPi approved these changes
all cases have been corrected

2022-11-22 12:31 UTC, psychocoderHPC approved these changes

2022-11-22 12:31 UTC, merged