example bunch: use incident filed laser
ComputationalRadiationPhysics/picongpu pull request #4449
Opened 2023-02-02 08:43 UTC by psychocoderHPC

- remove laser.param
- configure incidnet field laser equal to the old laser in laser.param
  - `png.param` normalize field values based on incident filed laser amplitude

- [ ] incident field laser with periodic boundaries must be fixed first!
- [ ] run a tests

# bunch example (step 700)
`./bin/picongpu -d 1 1 1 -g 128 1024 128 -s 2000 --periodic 1 0 1 --e_png.period 100 --e_png.axis yx --e_png.slicePoint 0.5 --e_png.folder pngElectronsYX`

![e_png_yx_0 5_000700](https://user-images.githubusercontent.com/4037125/216274329-7cc8a320-afb0-465b-b53f-066022eceb34.png)

You can see that boundaries are not periodic, the field must be equal in the transversal direction.

2023-03-01 06:45 UTC, psychocoderHPC commented
After rebasing against #4457 all works like expected

# step 700:
![e_png_yx_0 5_000700](https://user-images.githubusercontent.com/4037125/222064526-c0ad259e-c663-48db-a7c9-bf2bd6de4496.png)

2023-03-01 06:46 UTC, psychocoderHPC commented
@steindev PR can be reviewed

2023-03-02 12:30 UTC, PrometheusPi requested changes
Only minor housekeeping to remove unused pragmas

2023-03-02 12:30 UTC, PrometheusPi commented on share/picongpu/examples/Bunch/include/picongpu/param/incidentField.param
> +#    define PARAM_WAVE_LENGTH_SI 0.8e-6
is not used below - please remove

2023-03-02 12:30 UTC, PrometheusPi commented on share/picongpu/examples/Bunch/include/picongpu/param/incidentField.param
> +#    define PARAM_A0 8.0
is not used below, please remove

2023-03-02 12:30 UTC, PrometheusPi commented on share/picongpu/examples/Bunch/include/picongpu/param/incidentField.param
> +#    define PARAM_PULSE_LENGTH_SI 5.e-15
is not used below, please remove

2023-03-02 12:30 UTC, PrometheusPi commented on share/picongpu/examples/Bunch/include/picongpu/param/incidentField.param
> +                static constexpr float_64 PULSE_LENGTH_SI = 10.615e-15 / 4.0;
```suggestion
                static constexpr float_64 PULSE_LENGTH_SI = 2.65e-15;

```
old code reads (it is close but not exact)

2023-03-02 12:30 UTC, PrometheusPi commented on share/picongpu/examples/Bunch/include/picongpu/param/incidentField.param
> +                static constexpr float_64 FOCUS_POSITION_Z_SI = 0.0;
Just a general question: why is there a focus position for the plane wave anyway? It has no meaning.

2023-03-02 14:11 UTC, psychocoderHPC commented on share/picongpu/examples/Bunch/include/picongpu/param/incidentField.param
> +                static constexpr float_64 FOCUS_POSITION_Z_SI = 0.0;
because this is a requirement by the incident field laser

2023-03-02 14:12 UTC, psychocoderHPC commented
updated

2023-03-02 14:24 UTC, PrometheusPi approved these changes
Thanks for the quick adjustment @psychocoderHPC

2023-03-03 12:31 UTC, merged