[WIP] Introduce external beam for photon injection at a boundary
ComputationalRadiationPhysics/picongpu pull request #4510
Opened 2023-03-15 16:30 UTC by pordyna

# Photon injection at a simulation boundary
## Description
This PR introduces a new module `externalBeam` for injections of particles at a boundary. The code is written with two main assumptions:
 * The particles are photons and move with c
 * Particles don't enter the simulation at an angle (only along one of the simulation axes)

This is a part of the radiation transport prototype from my master thesis. The scattering and detection part will be introduced in separate PRs. 

This code reuses some of the code and therefore also some concepts from the old `xrayScattering`  plugin.  If we ever want to extend this to arbitrary incidence angles, we should probably switch to coordinate transforms and definitions from the incident field laser implementation.

## Status:
This PR is almost ready for review, the only thing missing is the readthedocs documentation. The question is if it is needed as long as the detection and scattering modules are not merged.

## Preview:
Photon density over time (png plugin output) from an old test:
![injectingPhotons](https://user-images.githubusercontent.com/41141557/225375542-02c6ca05-10b8-45cd-ab8b-391fc802b34f.gif)

## Tests:
This PR includes compile and runtime tests in `share/picongpu/tests/ExternalBeam` and  `share/picongpu/tests/ExternalBeamCompileTest`

@psychocoderHPC @HighIander

2023-04-04 14:52 UTC, psychocoderHPC commented
@pordyna We need to finish this PR soon to get it into 0.7.0. After 0.7.0 there will be extensive refactoring which is making every old param structure incompatible.

2023-04-04 15:11 UTC, psychocoderHPC requested changes

2023-04-04 15:11 UTC, psychocoderHPC commented on include/picongpu/particles/PhotonFunctors.hpp
> +                static const float_64 phaseDiffPerTimestep = fmod(omega * DELTA_T, 2.0 * PI);
should be `math::fmod`

2023-04-04 15:11 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/AxisSwap.def
> +                struct AxisSwap;
I do not understand what this class is doing. Need some more documentation and maybe an example.

2023-04-04 15:11 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/AxisSwap.def
> +                struct AxisSwap;
For me, it sounds like this is the functionality the `Accessor` of a vector in PMacc is providing.

2023-04-04 15:11 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/CoordinateTransform.def
> +                namespace detail
Please use a `struct` instead of the namespace. I do not see why a CONST_VECTOR is required, the user can not change this behavior anyway because this is part of the source code and not in params.
Maybe offline clarification is required.

2023-04-04 15:11 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/beamProfiles/GaussianProfile.hpp
> +                            float_X exponent = -0.5 * (tmp_x * tmp_x + tmp_y * tmp_y);
`0.5` should be `0.5_X`

2023-04-04 15:11 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/beamShapes/ConstShape.def
> +                        static constexpr bool limitStart = true;
Documentation required

2023-05-16 09:01 UTC, pordyna commented
@psychocoderHPC I'm getting the same kind of error now at https://github.com/ComputationalRadiationPhysics/picongpu/blob/70c22c3e219fa93ba0494057a25512e56a07d200/include/picongpu/particles/externalBeam/density/ProbingBeamImpl.hpp#L184
Again, the compiler is looking at the `simDim=3u` case, although the simulation is 2D and the if statement is constexpr.

2023-06-05 06:54 UTC, psychocoderHPC requested changes

2023-06-05 06:54 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/density/ProbingBeamImpl.hpp
> +            if constexpr(simDim == 2u)
ooks like a compiler bug is failing to see that if `simDim` is `2u` the else branch will not be executed.
suggested

```C++
totalCellOffsetVector.x() = totalCellOffset.x();
totalCellOffsetVector.y() = totalCellOffset.y();
if constexpr(simDim == 2)
    totalCellOffsetVector[2] = 0.0_X;
else
    totalCellOffsetVector[2] = totalCellOffset[2];
```

2023-06-07 09:46 UTC, psychocoderHPC requested changes

2023-06-07 09:46 UTC, psychocoderHPC commented on include/pmacc/math/vector/TwistComponents.hpp
> +            struct TwistComponents<T_Axes, const DataSpace<dim>>
You missed the include for `DataSpace`

2023-06-09 08:46 UTC, PrometheusPi commented
@pordyna can this be reviewed (and potentially merged)?

2023-06-09 08:48 UTC, pordyna commented
Yes, I will just squash the commits

2023-06-09 08:51 UTC, pordyna commented
@PrometheusPi ready for review

2023-06-12 08:56 UTC, pordyna commented
@psychocoderHPC CI crashed, can you restart?

2023-06-12 09:12 UTC, PrometheusPi commented
@pordyna CI restarted

2023-06-12 09:27 UTC, psychocoderHPC commented
@pordyna and @PrometheusPi The CI has currently issues, at least the NVIDIA runner, I opened already a ticket to solve the issues.

2023-06-14 13:47 UTC, pordyna commented
@psychocoderHPC @PrometheusPi Ci passed, ready for final review

2023-06-20 11:31 UTC, psychocoderHPC requested changes
I found some bugs and marked these clear with a **BUG** comment

2023-06-20 11:31 UTC, psychocoderHPC commented on docs/source/usage/workflows/particleBasedRadiationtransport.rst
> +It is possible to inject photon like macro particles at a simulation boundary for probing like setups.
@pordyna Do you spawn particles at the particle boundary? If not it is undefined behavior that happened with them when they cross the particle boundary.
So we need to take care that we spawn on the particle boundary and not cell zero.

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/param/speciesAttributes.param
> +    value_identifier(int16_t, voronoiCellId, -1);
Please remove this, `voronoiCellId` is already removed in the dev code base. I assume this is a left over from the past.

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/param/speciesAttributes.param
> +    value_identifier(float_X, polarizationAngle, 0._X);
Is this value in rad or degree? Please extent the description!

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/PhotonFunctors.hpp
> +
please remove one empty line

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/PhotonFunctors.hpp
> +            /** operator call for calling without a particle
please add an empty line

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/PhotonFunctors.hpp
> +                if(result < 0)
shoudl be `0.0`

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/PhotonFunctors.hpp
> +                /* phase phi = phi_0 - omega * t;
[optional] please add an empty line

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/PhotonFunctors.hpp
> +                if(result < 0)
should be `0.0`

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/StartAttributesImpl.hpp
> +                        , T_AccFunctor(accFunctor)...
```C++
T_AccStartPositionFunctor(std::forward<T_AccStartPositionFunctor>(accStartPositionFunctor))
, T_AccMomentumFunctor(std::forward<T_AccMomentumFunctor>(accMomentumFunctor))
,T_AccFunctor(std::forward<T_AccFunctor>(accFunctor))...
``` 
for perfect forwarding

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/StartAttributesImpl.hpp
> +                typename... T_Functor>
Maybe rename to `T_Functors` ?

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/ProbingBeam.hpp
> +            const float3_X offsetFromMiddlePoint_b{offsetTrans_b[0], offsetTrans_b[1], -1 * offsetParallel_b};
`-1.0_X *`

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/Side.hpp
> +                result[0] = static_cast<typename T_Vector::type>(-1.0) * twisted[0];
maybe defining a type is better than repeating the type evaluation

```
using ComponentType = typename T_Vector::type;
if constexpr(reverse_beam_x)
     result[0] = static_cast<ComponentType>(-1.0) * twisted[0];
...

```

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/Side.hpp
> +                result[0] = static_cast<typename T_Vector::type>(-1.0) * vector[0];
same as above, a intermediate type definition can increase the readability.

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/Side.hpp
> +            for(uint32_t i = 1u; 1 < T_Vector::dim; i++)
**BUG??** should it be `i < T_Vector::dim` ?? else this can be an endless loop.

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/Side.hpp
> +            for(uint32_t i = 1u; 1 < T_Vector::dim; i++)
**BUG??** should it be `i < T_Vector::dim` ?? else this can be an endless loop.

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/Side.hpp
> +    using XSide = ProbingCoordinates<XStartPosition, pmacc::math::CT::Int<2, 1, 0>, true, false, false>;
only a note: `true, false, true` that's a hard interface and always requires looking up into the interface description. 
enums can help to make it readable.

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/beamProfiles/GaussianProfile.hpp
> +                            constexpr float_X s_y = ParamClass::sigmaY_SI / UNIT_LENGTH;
Maybe `s_x` and `s_y` should be checked by a static_assert to avoid `zero` and a devision by zero in the next lines.

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/beamShapes/GaussianPulse.hpp
> +                                float_X exponent = -0.5 * (timeDist * timeDist / sigmaSquared);
`-0.5_X`

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/beamShapes/LorentzPulse.hpp
> +                        static constexpr float_X gamma = T_ParamClass::FWHM_SI / UNIT_TIME / 2.0;
`2.0_X`

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/beam/beamShapes/GaussianPulse.hpp
> +                        static constexpr float_64 conversion = 2.3548200450309493;
please add a comment what the magic number `2.3548200450309493` represent.

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/density/ProbingBeamImpl.hpp
> +            globalDomain_m.offset.y() += numSlides * localCells.y();
**BUG??** This look wrong, `subGrid.getGlobalDomain().offset` contains already all slides. You account twice for the slides in y direction.

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/density/ProbingBeamImpl.hpp
> +                boundary = globalCellOffset[d] == globalDomain_m.size[d] - 1;
The particle boundary index should be accounted.

2023-06-20 11:31 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/density/ProbingBeamImpl.hpp
> +                boundary = globalCellOffset[d] == 0;
The particle boundary index should be accounted.

2023-07-20 07:13 UTC, pordyna commented
@psychocoderHPC I introduced your requested changes with the last commit. I rerun the compile and the runtime tests on cpu and gpu on `fwk394`.

2023-07-21 15:14 UTC, pordyna commented
@psychocoderHPC I think the Ci failed, maybe it just needs a restart

2023-07-21 15:16 UTC, PrometheusPi commented
@pordyna I triggered the CI again.

2023-07-25 09:33 UTC, pordyna commented
I tried rebasing on dev again, maybe this helps

2023-08-31 08:37 UTC, psychocoderHPC commented
@pordyna could you please rebase this PR to check if all passed after we updated to the latest cupla/alpaka version.
In general all looks fine, we only need a green thumb from the CI.

2023-09-05 12:17 UTC, PrometheusPi commented
@pordyna and @psychocoderHPC I retriggered the CI - hope it passes this time.

2023-09-05 12:51 UTC, pordyna commented
@PrometheusPi It won't because of  the alpaka update, I need to move all the HDINLINEs to the front...

2023-09-05 12:58 UTC, PrometheusPi commented
@pordyna Thanks - I did not see that - that explains why I get a warning via mail.

2023-10-24 07:18 UTC, psychocoderHPC commented
only minor issues

```
/builds/hzdr/crp/picongpu/include/picongpu/../picongpu/simulation/stage/IterationStart.hpp:48:33:   required from here
/builds/hzdr/crp/picongpu/include/picongpu/../picongpu/particles/externalBeam/density/ProbingBeamImpl.hpp:137:28: error: unused variable 'numSlides' [-Werror=unused-variable]
  137 |             uint32_t const numSlides = MovingWindow::getInstance().getSlideCounter(currentStep);
      |                            ^~~~~~~~~
/builds/hzdr/crp/picongpu/include/picongpu/../picongpu/particles/externalBeam/density/ProbingBeamImpl.hpp:139:37: error: variable 'localCells' set but not used [-Werror=unused-but-set-variable]
  139 |             DataSpace<simDim> const localCells = subGrid.getLocalDomain().size;
      |                                     ^~~~~~~~~~
cc1plus: all warnings being treated as errors
```

2023-10-24 07:22 UTC, psychocoderHPC requested changes

2023-10-24 07:22 UTC, psychocoderHPC commented on include/picongpu/particles/externalBeam/StartAttributesImpl.hpp
> +                    rngHandleLocal.init(
please have a look here https://github.com/ComputationalRadiationPhysics/picongpu/pull/4685/files#diff-f8b4116fa9a761b713c81fdcca550f38c0af63541ee3c9c81853285d17cdc868R148 and https://github.com/ComputationalRadiationPhysics/picongpu/pull/4685#issue-1900792592

The way RNG numbers are mapped to worker threads has changed. SImple copy-past fix to this PR is required.

2023-12-15 10:14 UTC, closed without merging

2023-12-15 10:14 UTC, pordyna commented
Deiced to not continue with this PR. Other features like scattering and detection are far from being ready to merge in to mainline, and there is no benefit from having just the injection implemented. The full code is available on my fork and in my thesis https://zenodo.org/records/7928424.