update zenodo file and README
ComputationalRadiationPhysics/picongpu pull request #4525
Opened 2023-04-04 14:34 UTC by psychocoderHPC

- Update contributors for 0.7.0
`git log 0a885926683b960badbd5265bcd25e6c4e90d384..HEAD | grep Author | sort | uniq | sed "s/ \+/ /g; s/^ //" | cut -d" " -f2-3 | uniq`
- add missing names to README.txt thanks section

2023-04-04 15:14 UTC, BrianMarre commented
good to know that I am a developer, now ;)

2023-04-18 15:42 UTC, PrometheusPi requested changes
some minor changes are required
and the TU is sometimes written as `TU Dresden` and sometimes as `TU-Dresden`. 
Perhaps this should be consistent.

2023-04-18 15:42 UTC, PrometheusPi commented on .zenodo.json
> +      "affiliation":"HZDR, TU Dresden",
```suggestion
      "affiliation":"HZDR",
```

2023-04-18 15:42 UTC, PrometheusPi commented on .zenodo.json
> +      "affiliation":"HZDR",
```suggestion
      "affiliation":"HZDR, TU Dresden",
```

2023-04-18 15:42 UTC, PrometheusPi commented on .zenodo.json
> +      "affiliation":"HZDR",
```suggestion
      "affiliation":"HZDR, TU Dresden",
```

2023-04-24 08:14 UTC, psychocoderHPC commented
@PrometheusPi I fixed the affiliations

2023-04-24 09:03 UTC, PrometheusPi requested changes
Sorry @psychocoderHPC I found some more missing TU DD affilations.

2023-04-24 09:03 UTC, PrometheusPi commented on .zenodo.json
> +      "affiliation":"HZDR",
```suggestion
      "affiliation":"HZDR, TZ-Dresden",
```

Sorry, I did not see that before

2023-04-24 09:03 UTC, PrometheusPi commented on .zenodo.json
> +      "affiliation":"HZDR",
```suggestion
      "affiliation":"HZDR, TU Dresden",
```

2023-04-24 09:03 UTC, PrometheusPi commented on .zenodo.json
> +      "affiliation":"HZDR",
```suggestion
      "affiliation":"HZDR, TU Dresden",
```

2023-04-25 16:12 UTC, PrometheusPi approved these changes

2023-04-25 16:12 UTC, merged