improved debug bound checks for SetChargeState functor
ComputationalRadiationPhysics/picongpu pull request #4615
Opened 2023-06-27 09:40 UTC by BrianMarre

as discussed in [PR#4612](https://github.com/ComputationalRadiationPhysics/picongpu/pull/4612)

additional check for set `numberBoundElectrons` <= numberOfProtons species

2023-06-27 13:15 UTC, steindev requested changes, later dismissed

2023-06-27 13:15 UTC, steindev commented on include/picongpu/particles/atomicPhysics/SetChargeState.hpp
> +//! functor for setting the charge state of a macro particles
Remove 'a'

2023-06-27 13:15 UTC, steindev commented on include/picongpu/particles/atomicPhysics/SetChargeState.hpp
> +//! functor for setting the charge state of a macro particles
and write 'macro-particle' plz.

2023-06-28 12:25 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/SetChargeState.hpp
> +//! functor for setting the charge state of a macro particles
done

2023-06-28 15:16 UTC, psychocoderHPC approved these changes

2023-06-28 15:18 UTC, merged