add support for CMake option `alpaka_DISABLE_VENDOR_RNG`
ComputationalRadiationPhysics/picongpu pull request #4670
Opened 2023-09-07 08:32 UTC by psychocoderHPC

Add support for alpaka to disable the vendor random number generators. For PIConGPU the user should change the default `XorMin` RNG in `tandom.param` to `AlpakaRAnd` if `alpaka_DISABLE_VENDOR_RNG` is set to `ON`.

2023-09-07 09:17 UTC, PrometheusPi requested changes
minor style issues

2023-09-07 09:17 UTC, PrometheusPi commented on include/pmacc/random/distributions/normal/Normal_double.hpp
> +#endif
please add newline

2023-09-07 09:17 UTC, PrometheusPi commented on include/pmacc/random/distributions/normal/Normal_float.hpp
> +#endif
same here

2023-09-07 11:18 UTC, psychocoderHPC commented on include/pmacc/random/distributions/normal/Normal_float.hpp
> +#endif
done

2023-09-08 12:23 UTC, PrometheusPi approved these changes

2023-09-08 12:24 UTC, merged