refactor particle init kernel
ComputationalRadiationPhysics/picongpu pull request #4681
Opened 2023-09-13 08:57 UTC by psychocoderHPC

Motivation: The original implementation assumes that the number of slots in a frame and the number of cells within a supercell are equal. All particles from cell N were always created in the frame slot N too. In case there is a density gradient within the supercell frames are not filled fully which increases the memory footprint until the kernel fill gaps are called.

This PR decuples the number of cells in a supercell and the species frame size. Each thread searches a free slot within the frame and creates the particle in the slot, there is no implicit relation between the slot id in a frame and the cell where the particle is produced in. If the particle creation kernel is called multiple times for the same species the last frame will be filled first if possible.

2023-09-13 12:35 UTC, ikbuibui approved these changes
As discussed in the office, if we ensure that framesize >= supercell size, this looks good to me

2023-09-13 14:53 UTC, PrometheusPi requested changes
Just a typo. I am not the right person to check code functionality. Great, you checked that @ikbuibui. :+1:

2023-09-13 14:53 UTC, PrometheusPi commented on include/picongpu/particles/ParticlesInit.kernel
> +                /* Old value of the destination counter is stored to check later to check if a worker
Typo: double "to check" or do you really mean this?

2023-09-14 05:58 UTC, psychocoderHPC commented on include/picongpu/particles/ParticlesInit.kernel
> +                /* Old value of the destination counter is stored to check later to check if a worker
is a typo I will fix it

2023-09-14 11:54 UTC, PrometheusPi approved these changes

2023-09-15 16:10 UTC, merged