add missing euler number in ADK formula
ComputationalRadiationPhysics/picongpu pull request #4696
Opened 2023-09-28 08:54 UTC by BrianMarre

In our implementation of the ADK rate formula the sub term D was missing an euler number compared to our documentation and the reference Publication we were citing.

Since the reference publication does not make it clear whether it meant elementary charge or euler Number, I asked @n01r for clarification.

2023-09-28 11:48 UTC, BrianMarre commented
@PrometheusPi CI failed due to an internal error, please restart

2023-09-28 13:38 UTC, PrometheusPi submitted a review, later dismissed
Great catch! Mssing eEuler number from Stirling's approximation.

2023-09-28 14:34 UTC, PrometheusPi requested changes
just a small typo

2023-09-28 14:34 UTC, PrometheusPi commented on docs/source/models/field_ionization.rst
> +        Be aware that :math:`e` in :math:`D` denotes the euler number, not the elementary charge
```suggestion
        Be aware that :math:`e` in :math:`D` denotes the Euler's number, not the elementary charge
```
see: https://en.wikipedia.org/wiki/E_(mathematical_constant)

2023-09-29 12:08 UTC, BrianMarre commented on docs/source/models/field_ionization.rst
> +        Be aware that :math:`e` in :math:`D` denotes the euler number, not the elementary charge
Done

2023-09-29 15:26 UTC, PrometheusPi approved these changes

2023-10-02 15:42 UTC, merged