change order of PATH and fix wrong dev server path
ComputationalRadiationPhysics/picongpu pull request #4716
Opened 2023-10-23 10:43 UTC by PrometheusPi

This pull request 
 - changes the order of the `$PATH` in our example profiles since in the previous order any previously loaded profile will define the PIConGPU code version instead of the latest loaded version. 
  - while doing this manually (I should have automated it) I found a bug in the `$PATH` includes for all dev-server example profiles. These were introduced in #4086, #4183, and #4553 and this pull request fixes them too.
  
  @psychocoderHPC I think that this is not a critical bug that needs back-porting to 0.7.0 - do you agree?

2023-10-23 14:09 UTC, psychocoderHPC commented
0.7.0 has been out since last week. The next release will hopefully be faster out than the other.

2023-10-23 14:12 UTC, psychocoderHPC requested changes

2023-10-23 14:12 UTC, psychocoderHPC commented on etc/picongpu/aris-grnet/gpu_picongpu.profile.example
> +export PATH=$PICSRC:$PATH
Could you please remove this line from all files, we do not have binaries in the main directory. I do not know why we have this in at all.

2023-10-23 15:48 UTC, BrianMarre approved these changes

2023-10-24 09:01 UTC, PrometheusPi commented
@psychocoderHPC I removed all occurrences of `PATH=$PICSRC:$PATH` via:
```bash
for f in `grep -rl PATH . `; do sed -i -e '/export PATH=\$PICSRC:\$PATH/d' $f; done
``` 
and set the author to "Tools".

2023-10-24 11:50 UTC, psychocoderHPC approved these changes

2023-10-24 11:50 UTC, merged