refactor DataSpaceOperations
ComputationalRadiationPhysics/picongpu pull request #4719
Opened 2023-10-24 11:48 UTC by psychocoderHPC

- remove the method `map()` from `DataSpaceOperations`
- refcator `linearize()` for `math::Vector` and provide `mapToND()`
- use `linearize()` and `mapToND()` as replacement for `DataSpaceOperations::map()`

By using a better name instead of `map` for mapping to an ND-INdex and for linearizing an ND-Index the code is much better readable. Both functions work with N-dimensional Vectors and not only with up to 3-Dimensions.

- [ ] add documentation to `linearize()` and `mapToND`

CC-ing: @ikbuibui The upcoming refactoring could be interesting for your plugin.

2023-10-24 15:33 UTC, psychocoderHPC commented
note to myself: The class `MapToPos` should be removed too!

2023-10-25 08:33 UTC, ikbuibui commented on include/pmacc/math/vector/Vector.hpp
>          }
T_IntegralType linearIdx{idx[T_dim - 1]};
            for(int i = T_dim - 2; i >= 0; i--)
                linearIdx = linearIdx * pitchExtents[i] + idx[i];
            ```suggestion
            auto pitchExtents = size;
            for(uint32_t d = 1u; d < T_dim - 1u; ++d)
                pitchExtents[d] *= pitchExtents[d - 1u];

            T_IntegralType linearIdx = idx[0];
            for(uint32_t d = 1u; d < T_dim; ++d)
                linearIdx += pitchExtents[d - 1u] * idx[d];
            ```

2023-10-25 08:38 UTC, ikbuibui commented on include/pmacc/math/vector/Vector.hpp
> +        HDINLINE T_IntegralType linearize(
T_IntegralType linearIdx{idx[T_dim - 1]};
        for(int i = T_dim - 2; i >= 0; i--)
            linearIdx = linearIdx * size[i] + idx[i];

2023-10-25 08:39 UTC, ikbuibui commented on include/pmacc/math/vector/Vector.hpp
> +        HDINLINE T_IntegralType linearize(
An alternative implementation can be like this. This formulation should also work for mapToND

2023-10-25 14:49 UTC, psychocoderHPC commented on include/pmacc/math/vector/Vector.hpp
> +        HDINLINE T_IntegralType linearize(
added your suggestions.

2023-10-30 22:04 UTC, PrometheusPi requested changes
just a very minor typo

2023-10-30 22:04 UTC, PrometheusPi commented on include/pmacc/math/vector/Vector.hpp
> +        /** Give the linear index of a N-dimensional index within an N-dimensional index space.
```suggestion
        /** Give the linear index of an N-dimensional index within an N-dimensional index space.
```

2023-11-01 15:01 UTC, ikbuibui commented
I think it would be helpful to edit `docs/source/prgpatterns/lockstep.rst` to reflect the change that the linearIdx from the lockstep should be handled as int32_t instead of uint32_t.

2023-11-08 09:27 UTC, psychocoderHPC commented on include/pmacc/math/vector/Vector.hpp
> +        /** Give the linear index of a N-dimensional index within an N-dimensional index space.
fixed

2023-11-08 09:29 UTC, psychocoderHPC commented
> I think it would be helpful to edit `docs/source/prgpatterns/lockstep.rst` to reflect the change that the linearIdx from the lockstep should be handled as int32_t instead of uint32_t.

Changing the first lambda parameter to int is not required. In the examples, we do not use the linearizing functions.
Using `int` is only required in case you call methods that require `int` and you do not static cast.

2023-11-09 14:33 UTC, psychocoderHPC commented
@PrometheusPi PR can be merged

2023-11-09 15:33 UTC, ikbuibui commented
The binning plugin is still using the DataSpaceOperations map function (pre refactor), the occurrence needs to be fixed before merging

2023-11-09 15:41 UTC, psychocoderHPC commented
> The binning plugin is still using the DataSpaceOperations map function (pre refactor), the occurrence needs to be fixed before merging

Fixed, @PrometheusPi PR can be merged after the CI passed

2023-11-09 20:24 UTC, PrometheusPi approved these changes

2023-11-09 20:27 UTC, PrometheusPi requested changes
There is a compile bug in:
```
/builds/hzdr/crp/picongpu/include/picongpu/../picongpu/param/binningSetup.param:55:68: error: no member named 'map' in 'pmacc::DataSpaceOperations<2U>'
                    = pmacc::DataSpaceOperations<SIMDIM>::template map<SuperCellSize>(linearCellIdx);
 ```
 `map` is not known. 
 I think this file was just forgotten.

2023-11-10 08:38 UTC, psychocoderHPC commented
> There is a compile bug in:
> 
> ```
> /builds/hzdr/crp/picongpu/include/picongpu/../picongpu/param/binningSetup.param:55:68: error: no member named 'map' in 'pmacc::DataSpaceOperations<2U>'
>                     = pmacc::DataSpaceOperations<SIMDIM>::template map<SuperCellSize>(linearCellIdx);
> ```
> 
> `map` is not known. I think this file was just forgotten.

should be fixed now

2023-11-10 15:19 UTC, PrometheusPi approved these changes

2023-11-10 15:20 UTC, merged