Add prepulse duration option to ExpRampWithPrepulse
ComputationalRadiationPhysics/picongpu pull request #4725
Opened 2023-11-01 14:39 UTC by pordyna

Adds an option for setting the prepulse duration independently of the main pulse duration (in `ExpRampWithPrepulse`). 
Also removes a static assert in  `ExpRampWithPrepulse` and some old, unused, already commented out code. @wmles already removed the assert in his production code. The simulation can be valid also when the requirement is not full field.

2023-11-02 16:59 UTC, PrometheusPi requested changes
some minor remarks on code style - code itself is fine

2023-11-02 16:59 UTC, PrometheusPi commented on include/picongpu/fields/incidentField/profiles/ExpRampWithPrepulse.def
> +                     *  PREPULSE_DURATION_SI = FWHM_of_Intensity   / [ 2*sqrt{ 2* ln(2) } ]
This does not fulfil our code style 
please adjust indentation to line 63 and 69. 
Otherwise, our CI gets angry

2023-11-02 16:59 UTC, PrometheusPi commented on include/picongpu/fields/incidentField/profiles/ExpRampWithPrepulse.hpp
> +                         *
the same her 
(And if I check your code I get some strange carrier return symbols - not sure if they come from my or your side)

2023-11-02 16:59 UTC, PrometheusPi commented on include/picongpu/fields/incidentField/profiles/ExpRampWithPrepulse.hpp
> +                                                                Unitless::PULSE_DURATION);
Here we need a line break according to code style. 
```suggestion
                    env += (1._X - ramp_when_peakpulse)
                        * gauss(runTime - Unitless::endUpramp, Unitless::PULSE_DURATION);
```

2023-11-02 16:59 UTC, PrometheusPi commented on share/picongpu/examples/LaserWakefield/include/picongpu/param/incidentField.param
> +                     *  PREPULSE_DURATION_SI = FWHM_of_Intensity   / [ 2*sqrt{ 2* ln(2) } ]
same as above - indentation should match line 283 and 289

2023-11-03 12:24 UTC, PrometheusPi submitted a review, later dismissed

2023-11-06 10:45 UTC, PrometheusPi commented
@pordyna there is a compile error in the FoilLCT example that triggers:
`picongpu/include/picongpu/fields/incidentField/profiles/ExpRampWithPrepulse.hpp` Line 79
The variable 'PREPULSE_DURATION_SI' has not been defined.

2023-11-30 12:21 UTC, psychocoderHPC commented
@PrometheusPi It looks like @pordyna added your suggestions

2023-12-05 09:26 UTC, PrometheusPi approved these changes

2023-12-05 09:34 UTC, PrometheusPi commented
Dear @ComputationalRadiationPhysics/picongpu-developers this is a breaking change. Please adjust your param files.

2023-12-05 09:35 UTC, merged