Add openPMD-viewer test
ComputationalRadiationPhysics/picongpu pull request #4747
Opened 2023-11-21 07:48 UTC by max-lehman14

A simple example is used and the input parameters are compared to the readout of the openPMD-viewer. This test involves the electromagnetic fields, electron and ion charge density, particle positions and momenta.

2023-11-21 18:38 UTC, psychocoderHPC commented
Please reformat your python files to be `flake8` conform.

2023-11-30 14:57 UTC, max-lehman14 commented
@PrometheusPi I am using openpmd_viewer 1.7.0

2023-12-08 13:03 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/README.rst
Please add a description how to execute the test manually.

2023-12-08 13:04 UTC, PrometheusPi commented
Please add a [`requirements.txt`](https://learnpython.com/blog/python-requirements-file/)

2023-12-14 17:14 UTC, PrometheusPi commented
I tested the new test with
```bash
./picongpu/share/picongpu/tests/openPMD-viewer-test/bin/ci.sh picongpu/share/picongpu/tests/openPMD-viewer-test/ ./run01
```
on hemera and it works fine. 
Will do a proper code review asap.

2023-12-20 12:23 UTC, PrometheusPi requested changes
There are a few (minor) code changes - see comments. 

I tested the code to fail by changing the PIConGPU param files to disagree with the (python) parameter dictionary against it was compared. 
That lead to the intended errors when:
 - changing the background electric field
 - changing the gamma from `1.021` to `2.021`
 - not adding ion species 

When rebasing against the mainline dev, I assume one gets compile time errors. 
(I currently could not test that due to high work load on hemera's v100)
I will test it myself asap, but_
--> Please rebase against the current `dev`

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/bin/ci.sh
> +# Authors: Mika Soren Voss, Hannes Wolf, Klaus Steiniger
please add your name

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/README.rst
> +This test reads out openPMD-viewer data and checks if it matches the input values to see if users can rely on the output.
```suggestion
This test reads out openPMD data via the openPMD-api and checks if it matches the input values to test if users can rely on the output.
```

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/README.rst
> +This test reads out openPMD-viewer data and checks if it matches the input values to see if users can rely on the output.
minor rewording

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/bin/ci.sh
> +  echo "                                         Default: current directory"
please adjust indentation to be on one level

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/bin/ci.sh
> +currentPath=$(absolute_path $currentPath)
please remove unused code

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/bin/ci.sh
> +  echo -e "$(help)"
optional:
could you please output an extra info on what went wrong before yu print the help? 
Like 
```bash
echo Two arguments are required, $# given!
```

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/bin/ci.sh
> +exit $ret
please add a newline

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/bin/validate.sh
> +  fi
This is not needed. 
If there is no path given, `getopt` will create an error `getopt: option requires an argument -- 'd'  `.
If one enforces an empty input via `./bin/validate.sh -d "" ` line 52 will not provide an correct input. 
Thus, please just remove these lines.

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/dimension.param
this is a (outdated) copy of the default setup. Please remove. We can rely on the default here.

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/density.param
This file is most likely outdated and will cause issues with the current `dev`- I will check this asap (see later)

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/fieldBackground.param
see comment on rebasing

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/fieldBackground.param
> +            return float3_X(-30.0e2 / m_unitField[1], -20.0e4 / m_unitField[1], -10.0e6 / m_unitField[1]);
```suggestion
            return float3_X(-30.0e2 / m_unitField[0], -20.0e4 / m_unitField[1], -10.0e6 / m_unitField[2]);
```
Please divide by the unit in each dimension. (Should cause no problem here, since in this case, they are the same in each dimension.)

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/fieldBackground.param
> +            return float3_X(25.0 / m_unitField[1], -50.0 / m_unitField[1], 50.0 / m_unitField[1]);
same as above

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/grid.param
see comment on rebasing

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/grid.param
most likely for this file it should not matter

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/particleFilters.param
Is this file used? If not, please remove.

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/speciesDefinition.param
> +#endif
not needed, please remove

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/speciesDefinition.param
> +#endif
not needed, please remove

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/speciesDefinition.param
see comment on rebasing (might not affect this file)

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/particle.param
> +            using AssignXDriftNegative = unary::Drift<DriftParamNegative, pmacc::math::operation::Assign>;
not used, please remove

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/particle.param
> +            using AddTemperature = unary::Temperature<TemperatureParam>;
not used, please remove

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/speciesInitialization.param
see comment on rebasing (most likely unaffected)

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +print(openpmd_viewer.__version__)
```suggestion
print("openPMD-viewer version:", openpmd_viewer.__version__)
```
Just to let the user see what the printed number actually means.

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +    * 1e25,
could the equation be formatted nicer without causing linter issues?

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +v = gamma * (spc.c * (gamma**2 - 1) ** (1 / 2)) / spc.c
please move to before your `field_param` dictionary and use `gamma` in the equation

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +    * 1e25,
if you move the `gamma` code below in front of this dictionary definition, you could use gamma instead of the magic umber `1.021`
```suggestion
    "e_all_energyDensity": spc.m_e
    * spc.c**2
    * (gamma - 1)
    * 1e25,
```

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +
please define
```suggestion

base_density = 1.0e25
```
and use it in the dictionary below

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +    "e_all_chargeDensity": -spc.elementary_charge * 1e25,
```suggestion
    "e_all_chargeDensity": -spc.elementary_charge * base_density,
```

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +    * 1e25,
```suggestion
    "e_all_energyDensity": spc.m_e
    * spc.c**2
    * (1.021 - 1)
    * base_density,
```

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/include/picongpu/param/particle.param
> +            using AssignXDriftPositive = unary::Drift<DriftParamPositive, pmacc::math::operation::Assign>;
please rename since the name is misleading (it's not a drift in x anymore) 
(and adjust it where needed elsewhere)

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +                eps_s = 1e-9
could this be defined outside the loop (e.g. in the beginning of the code as a setup parameter)?

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +                eps_s = 1e-9
perhaps even as part of your parameter dictionary.

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +                field_param[f"{density}"] * 1e-1
see comment before: please define this in your parameters dictionary (or a separate epsilon dictionary)

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +                field_param[f"{density}"] * 1e-1
what is the meaning of `eps_s` and `eps_l` please add a comment

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +                field_param[f"{density}"] * 1e-1
```
                field_param[f"{density}"] * 1e-1
```
Why do we accept an error of 10%? Is this due to the particle motion or can this be reduced?

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +        eps = 0.1
see comment above on epsilons

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +sys.exit(not bool_pass)
please add a comment on why we needed to negate the return value - otherwise this is really confusing

2023-12-20 12:23 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/README.rst
> +To run this test, one has to execute ci.sh with the location of the input and output directory.
Could you please add a codeblock to show that?

2023-12-20 20:23 UTC, PrometheusPi commented
I rebased against the current `dev`. There is no compile isssue - thus `density.param` is still fine. 
Thus, @max-lehman14 please just a code commented above.

2024-01-05 13:34 UTC, max-lehman14 commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +    * 1e25,
> could the equation be formatted nicer without causing linter issues?

what do you mean by linter issues?

2024-01-05 14:03 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +    * 1e25,
The code is quite widely spread over multiple lines. Perhaps there is a more readable and compact form that does not trigger python style issues (=linter issues).

2024-01-09 18:02 UTC, PrometheusPi commented
@max-lehman14 There are still compile errors in your code ee.g.: 
```
error: 'AssignXDriftPositive' is not a member of 'picongpu::particles::manipulators';
```

2024-04-24 12:45 UTC, BrianMarre commented
@max-lehman14 the CI fails due to an undocumented change in behaviour in recent typeguard versions fixed by PR #4861, please rebase to the current dev

2024-04-26 13:56 UTC, PrometheusPi requested changes
Looks very good @max-lehman14 just a few minor issues left.

2024-04-26 13:56 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/README.rst
> +This test reads out openPMD data via the openPMD-api and checks if it matches the input values to test if users can rely on the output.
```suggestion
This test reads out openPMD data via the openPMD-viewer and checks if it matches the input values to test if users can rely on the output.
```

2024-04-26 13:56 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +v = gamma * (spc.c * (gamma**2 - 1) ** (1 / 2)) / spc.c
Could you add a comment that says what this variable does?

2024-04-26 13:56 UTC, PrometheusPi commented on share/picongpu/tests/openPMD-viewer-test/lib/python/test/param-test.py
> +# Define uncertainties
there seem to be no uncertainties defined here

2024-05-14 07:51 UTC, PrometheusPi commented
@max-lehman14 I think your code base is too old and thus triggers a CI error that your actual code does not cause. 
Please update the code of your pull request via: `git pull --rebase mainline dev` and then push the branch to GitHub. We can do this together tomorrow of needed.

2024-05-15 08:33 UTC, PrometheusPi approved these changes

2024-05-29 07:45 UTC, PrometheusPi commented
@max-lehman14 perfect - could you please squash all your commits to one.

2024-05-29 14:14 UTC, merged