add README to KHI test
ComputationalRadiationPhysics/picongpu pull request #4761
Opened 2023-12-05 09:59 UTC by PrometheusPi

The KHI test was missing a README file. This pull request adds a short description? 
@psychocoderHPC should I also add a quick example on how to run it?

2023-12-06 16:35 UTC, steindev requested changes
Please see comments.

2023-12-06 16:35 UTC, steindev commented on share/picongpu/tests/KHI_growthRate/README.rst
> +This KHI growth rate test simulates a shear-flow instability known as the Kelvin-Helmholtz Instability in a sub-relativistic setup as studied in [Alves12]_, [Grismayer13]_, [Bussmann13]_. The setup u
'the PIConGPU'?

2023-12-06 16:35 UTC, steindev commented on share/picongpu/tests/KHI_growthRate/README.rst
> +
A 'How to Execute' section would be very helpful.

2023-12-06 16:35 UTC, steindev commented
And is this text supposed to appear in the readthedocs? By now it is not included.

2024-01-15 09:17 UTC, psychocoderHPC commented
@PrometheusPi Could you please finish this PR.

2024-02-05 10:29 UTC, steindev requested changes
Some typos remain. Please squash all commits before next push.

2024-02-05 10:29 UTC, steindev commented on share/picongpu/tests/KHI_growthRate/README.rst
> +This KHI growth rate test simulates a shear-flow instability known as the Kelvin-Helmholtz Instability in a sub-relativistic setup as studied in [Alves12]_, [Grismayer13]_, [Bussmann13]_. The setup u
theroretic -> theoretical
The tests only passes ... -> The tests only pass ...

2024-02-05 10:29 UTC, steindev commented on share/picongpu/tests/KHI_growthRate/README.rst
> +       *dc-magnetic-field generation in unmagnetized shear flows*,
Phys Rev writes the title as 'dc-Magnetic-Field Generation in Unmagnetized Shear Flows'.

2024-02-26 15:36 UTC, PrometheusPi commented
@steindev I added all your suggestions. And I added a comment on the need of `$PICSRC` which we found out today with @psychocoderHPC.

2024-05-21 15:05 UTC, chillenzer approved these changes
In the hope of steering this into the direction of a merge: Looks good. Title of the PR is a bit misleading as you added a full section to the docs. Maybe you want to change this, so our [automatic changelog](https://github.com/ComputationalRadiationPhysics/picongpu/pull/4908) is more accurate to start with.

2024-06-05 08:21 UTC, PrometheusPi commented
ping @psychocoderHPC and @steindev: ready for merge

2024-06-06 06:53 UTC, steindev approved these changes

2024-06-06 06:53 UTC, merged