Implement checkpoint and restart capability to the binning plugin
ComputationalRadiationPhysics/picongpu pull request #4766
Opened 2023-12-11 09:42 UTC by ikbuibui

Implement checkpoint and restart capability to the binning plugin. 
Checkpointing and restarting is called by PIConGPU for the binningDispatcher, which handles checkpoint and restart for all individual "binners".
Currently the checkpoint information is stored in the default checkpoint directory, in a sub-folder called binningOpenPMD, and the file name and file type for the checkpoints aren't seperately configurable. File name and file type are the same as the ones created during a normal execution data dump.
Also added some previously missing includes

2023-12-11 10:32 UTC, psychocoderHPC requested changes
only small changes required

2023-12-11 10:32 UTC, psychocoderHPC commented on include/picongpu/plugins/binning/Binner.hpp
> +                auto bufferExtent = this->histBuffer->getDeviceBuffer().getDataSpace();
can be `getHostBuffer()`

2023-12-11 10:32 UTC, psychocoderHPC commented on include/picongpu/plugins/binning/BinningCreator.hpp
> +             * @param binnerOutputName filename for openPMD output. It musit be unique or will cause overwrites during
`musit`-> must`

2023-12-11 11:23 UTC, ikbuibui commented on include/picongpu/plugins/binning/Binner.hpp
> +                auto bufferExtent = this->histBuffer->getDeviceBuffer().getDataSpace();
Yes, you are right. Also changed to getHostBuffer() in line 199.

2023-12-11 11:27 UTC, ikbuibui commented on include/picongpu/plugins/binning/BinningCreator.hpp
> +             * @param binnerOutputName filename for openPMD output. It musit be unique or will cause overwrites during
fixed

2023-12-12 13:09 UTC, psychocoderHPC approved these changes

2023-12-12 13:09 UTC, merged