Add unit test for `moveParticle`
ComputationalRadiationPhysics/picongpu pull request #4783
Opened 2024-01-12 15:31 UTC by chillenzer

Also mostly supposed as a warm-up for me. Nothing fancy.

Basically two changes:
1. Add `include/...` to the unit test directory to make `simulation_defines.hpp` usable (using it to run tests for 2D and 3D).
2. Adding the test file successively.

Caveats we discussed:
This is currently very simple and does not take into account the accelerators at all. This hugely simplifies setup but doesn't help with compiler specific bugs. Particularly, the one about rounding errors will crucially depend on this and is probably insufficiently covered by the current approach.

PS: Feel free to request history cosmetics to your liking.

2024-01-16 09:09 UTC, psychocoderHPC requested changes

2024-01-16 09:09 UTC, psychocoderHPC commented on share/picongpu/unit/MoveParticle.cpp
> +        return isApproxEqual(pos, other.pos) and localCellIdxValue == other.localCellIdxValue
Can we stay with the primary representation of `and` (`&&`).
This simplifies reading the code if you do not have syntax highlighting and is more in line with the current code base. 
There was a discussion in the past about these alternatives but unfortunately, I do not find it again .-(

2024-01-16 09:09 UTC, psychocoderHPC commented on share/picongpu/unit/MoveParticle.cpp
> +        CHECK(not leftSuperCell);
please use `!`

2024-01-16 09:09 UTC, psychocoderHPC commented on share/picongpu/unit/MoveParticle.cpp
> +        CHECK(not leftSuperCell);
please use `!`

2024-01-16 09:09 UTC, psychocoderHPC commented on share/picongpu/unit/MoveParticle.cpp
> +        CHECK(not leftSuperCell);
`!`

2024-01-16 09:09 UTC, psychocoderHPC commented on share/picongpu/unit/MoveParticle.cpp
> +        CHECK(not leftSuperCell);
`!`

2024-01-16 09:09 UTC, psychocoderHPC commented on share/picongpu/unit/MoveParticle.cpp
> +        CHECK(not leftSuperCell);
`!`

2024-01-16 09:09 UTC, psychocoderHPC commented on share/picongpu/unit/MoveParticle.cpp
> +        newPos[0] = -1.e-9;
Maybe we should use `epsilon/2._X` here to cover single in double precision?

2024-01-16 09:09 UTC, psychocoderHPC commented on share/picongpu/unit/MoveParticle.cpp
> +        CHECK(not leftSuperCell);
`!`

2024-01-16 10:31 UTC, chillenzer commented on share/picongpu/unit/MoveParticle.cpp
> +        newPos[0] = -1.e-9;
Interestingly, epsilon/2 didn't work on my machine. Had to be at least epsilon/4. But anyhow, it's fixed. Thanks for catching this!

2024-01-17 08:20 UTC, psychocoderHPC approved these changes

2024-01-17 08:20 UTC, merged