rename `getDataSpace` to `capacityND`
ComputationalRadiationPhysics/picongpu pull request #4851
Opened 2024-03-22 10:44 UTC by psychocoderHPC

- rename `getDataSpace` to `capacityND`
- rename `getDataSpaceWithoutGuarding` to `capacityWithoutGuardingND`

**Note:** I only renamed the functions, I did not update the variable names inside of function where the changed functions are used.

2024-03-22 11:39 UTC, ikbuibui submitted a review, later dismissed

2024-03-25 10:27 UTC, chillenzer approved these changes
Okay. Very straightforward. Still one question: I'm totally with you that a "capacity" is a property of a buffer. Is it also a property of a grid layout? (Not sure if this is understandable via text, we can discuss offline if not.)

2024-03-25 16:40 UTC, psychocoderHPC commented
> Okay. Very straightforward. Still one question: I'm totally with you that a "capacity" is a property of a buffer. Is it also a property of a grid layout? (Not sure if this is understandable via text, we can discuss offline if not.)

NO should be size for the grid layout. Search and replace bug. I will fix it.

2024-03-25 18:20 UTC, psychocoderHPC commented
I updated the PR

2024-03-26 09:20 UTC, ikbuibui requested changes

2024-03-26 09:20 UTC, ikbuibui commented on include/pmacc/fields/operations/AddExchangeToBorder.hpp
> +                    auto const numGuardSuperCells = destBuffer.getGridLayout().sizeND() / SuperCellSize::toRT();
```suggestion
                    auto const numGuardSuperCells = destBuffer.getGridLayout().guardSizeND() / SuperCellSize::toRT();
```

2024-03-26 16:12 UTC, ikbuibui requested changes

2024-03-26 16:12 UTC, ikbuibui commented on share/pmacc/examples/heatEquation2D/main.cpp
> +    auto mapping = std::make_unique<MappingDesc>(layout.capacityND(), guardingSuperCells);
```suggestion
    auto mapping = std::make_unique<MappingDesc>(layout.sizeND(), guardingSuperCells);
```

2024-03-26 16:12 UTC, ikbuibui commented on share/pmacc/examples/gameOfLife2D/include/Simulation.hpp
> +            evo.init(layout.capacityND(), Space::create(1));
```suggestion
            evo.init(layout.sizeND(), Space::create(1));
```

2024-03-27 13:15 UTC, psychocoderHPC commented on share/pmacc/examples/heatEquation2D/main.cpp
> +    auto mapping = std::make_unique<MappingDesc>(layout.capacityND(), guardingSuperCells);
done

2024-03-27 13:16 UTC, ikbuibui approved these changes

2024-03-28 12:24 UTC, merged