openPMD: add parameter `particleIOChunkSize`
ComputationalRadiationPhysics/picongpu pull request #4874
Opened 2024-04-19 14:51 UTC by psychocoderHPC

Allow defining a chunk size which is used to write particles with multiple write calls instead of a single.
The benefits are that the host memory footprint to write particles with the Adios2 bp5 engine is drastically reduced.
For systems like ORNL Frontier where the amount of GPU memory is equal to the host memory, we can now fill the full GPU memory with particles without running out of memory during the IO.

By default `particleIOChunkSize` is set to 10 GiB which is a reasonable value that our data chunks are not too small but typically fit for a system with a low amount of host memory.

Field IO is not affected by this feature.

- [ ] run test on frontier
- [ ] hdf5/bp4 and bp5 test on our dev server

2024-04-19 14:56 UTC, psychocoderHPC commented
@franzpoeschel could you please check if I implemented the json/toml CLI argument correctly.

2024-04-19 15:39 UTC, psychocoderHPC commented on include/picongpu/plugins/openPMD/WriteSpecies.hpp
> +                        log<picLog::INPUT_OUTPUT>("openPMD: (end) write particle records for %1%, dumping round %2%")
Comment must be moved two lines up to have the correct iteration in the log message.

2024-04-19 15:40 UTC, psychocoderHPC commented on include/pmacc/mappings/kernel/RangeMapping.hpp
> +     * Adheres to the MapperConcept.
????

2024-04-19 15:40 UTC, psychocoderHPC commented on include/pmacc/mappings/kernel/RangeMapping.hpp
> +        HDINLINE uint32_t last() const
comments are missing for this and other mehods

2024-04-19 15:44 UTC, psychocoderHPC commented on include/pmacc/particles/memory/dataTypes/Particle.hpp
> +        /** Size of an particle if all data members started without padding in a contigious data chunk.
The sum of the bytes of all value identifiers of a particle.

2024-04-22 09:46 UTC, franzpoeschel commented on include/picongpu/plugins/openPMD/openPMDWriter.hpp
> +                {&particleIOChunkSize, "particleIOChunkSize", &PluginParameters::particleIOChunkSizeString}};
The only reason why this is fixed to `std::string` parameters is because other types were not needed so far. We can also extend this to allow other types somehow.
However, I'm not sure if this should be done for memory sizes, because in future we might want to allow things like `--openPMD.particleIOChunkSize 10Gb`.

2024-04-22 10:47 UTC, psychocoderHPC commented on include/picongpu/plugins/openPMD/openPMDWriter.hpp
> +                {&particleIOChunkSize, "particleIOChunkSize", &PluginParameters::particleIOChunkSizeString}};
We can stay with string, it's not a big issue and as you suggested it provides the possibility to allow postfix for the unit later on.

2024-04-22 13:28 UTC, franzpoeschel commented
Running some benchmarks with Heaptrack:

`picongpu -d 1 1 1 -g 192 2048 192 -s 300 --openPMD.period 100 --openPMD.ext bp5 --openPMD.particleIOChunkSize 1024`
![Bildschirmfoto vom 2024-04-22 14-37-12](https://github.com/ComputationalRadiationPhysics/picongpu/assets/14241876/d3f00d16-1f0b-4e59-9465-a532d42e3db3)

`picongpu -d 1 1 1 -g 192 2048 192 -s 300 --openPMD.period 100 --openPMD.ext bp5 --openPMD.particleIOChunkSize 1024 --openPMD.dataPreparationStrategy mappedMemory`
![Bildschirmfoto vom 2024-04-22 14-57-14](https://github.com/ComputationalRadiationPhysics/picongpu/assets/14241876/8b5c18d1-1abf-4351-8478-d4baa63bee0d)

`picongpu -d 1 1 1 -g 192 2048 192 -s 300 --openPMD.period 100 --openPMD.ext bp5`
![Bildschirmfoto vom 2024-04-22 15-04-01](https://github.com/ComputationalRadiationPhysics/picongpu/assets/14241876/7cf19455-bf3a-4fb3-9dba-d7564b88f6f6)

`picongpu -d 1 1 1 -g 192 2048 192 -s 300 --openPMD.period 100 --openPMD.ext bp5 --openPMD.dataPreparationStrategy mappedMemory`
![Bildschirmfoto vom 2024-04-22 15-27-29](https://github.com/ComputationalRadiationPhysics/picongpu/assets/14241876/890cf37b-0b54-4dda-947c-2b6861287276)


**Before this PR:**

`picongpu -d 1 1 1 -g 192 2048 192 -s 300 --openPMD.period 100 --openPMD.ext bp5`
![Bildschirmfoto vom 2024-04-22 15-16-25](https://github.com/ComputationalRadiationPhysics/picongpu/assets/14241876/8e946764-4097-4c7f-895c-f03f9b4d9a6f)


`picongpu -d 1 1 1 -g 192 2048 192 -s 300 --openPMD.period 100 --openPMD.ext bp5 --openPMD.dataPreparationStrategy mappedMemory`
![Bildschirmfoto vom 2024-04-22 15-20-10](https://github.com/ComputationalRadiationPhysics/picongpu/assets/14241876/e163a73d-a630-45c8-92cd-ca22d0c6049b)

2024-04-23 06:10 UTC, psychocoderHPC commented
@franzpoeschel Thanks for running the benchmarks. Could you rerun once 
`picongpu -d 1 1 1 -g 192 2048 192 -s 300 --openPMD.period 100 --openPMD.ext bp5 --openPMD.particleIOChunkSize 128 --openPMD.dataPreparationStrategy mappedMemory`

This should show a clear difference in the memory footprint but will run slower. In the current plot the difference between before and after is hard to see expect some dips during the write because the example is not writing to much data.

2024-04-23 08:24 UTC, franzpoeschel commented
I was wondering where the 2GB come from but that's the BufferChunkSize of BP5, Heaptrack records the virtual memory. Let me run again with a changed size. We could theoretically change the default size here, but I'm not sure we should since the overhead is only virtual.

![Bildschirmfoto vom 2024-04-23 10-22-41](https://github.com/ComputationalRadiationPhysics/picongpu/assets/14241876/810e0a63-35f9-4bce-97f8-56719dc5471b)

2024-04-23 08:29 UTC, franzpoeschel commented
![Bildschirmfoto vom 2024-04-23 10-28-54](https://github.com/ComputationalRadiationPhysics/picongpu/assets/14241876/58fa99d9-3c38-4bd2-8af4-ba1e827be21c)
This is with `picongpu -d 1 1 1 -g 192 2048 192 -s 300 --openPMD.period 100 --openPMD.ext bp5 --openPMD.particleIOChunkSize 128 --openPMD.dataPreparationStrategy mappedMemory --openPMD.json '{"adios2":{"engine":{"parameters":{"BufferChunkSize": "200Mb"}}}}'`

2024-04-23 14:13 UTC, psychocoderHPC commented
explanation: The 300MiB spike at the beginning is coming from the fields. Currently we only chunk particle IO.

Chunking of field IO is much easier and can be implemented later if needed.

2024-04-23 15:03 UTC, franzpoeschel commented
Since the particles spread over different components (x, y, z), the BufferChunkSize could be turned even smaller probably, but I think the profiles show that this PR does what it intends to. Otherwise, I don't see anything that is obviously wrong.

2024-04-23 15:03 UTC, franzpoeschel approved these changes

2024-04-24 07:29 UTC, psychocoderHPC commented
@ComputationalRadiationPhysics/picongpu-maintainers PR can be merged

2024-04-24 10:36 UTC, PrometheusPi requested changes
just a minor typo

2024-04-24 10:36 UTC, PrometheusPi commented on docs/source/usage/plugins/openPMD.rst
> +                                      Currently the memory footprint is only reduced bp5 is used, HDF5 and bp4 does not support partial data dump.
This is not a sentence. Is an if missing? 
```suggestion
                                      Currently the memory footprint is only reduced if bp5 is used, HDF5 and bp4 does not support partial data dump.
```

2024-04-24 10:39 UTC, PrometheusPi commented on docs/source/usage/plugins/openPMD.rst
> +                                      Currently the memory footprint is only reduced bp5 is used, HDF5 and bp4 does not support partial data dump.
Discussed *offline* with @psychocoderHPC: the typo will be fixed in a followup pll request.

2024-04-24 10:39 UTC, PrometheusPi approved these changes

2024-04-24 10:39 UTC, merged

2024-04-24 10:39 UTC, chillenzer reviewed
Sorry, had a half-finished review open. Not yet through but maybe you want to consider this already.

2024-04-24 10:39 UTC, chillenzer commented on docs/source/usage/plugins/openPMD.rst
> +                                      Currently the memory footprint is only reduced bp5 is used, HDF5 and bp4 does not support partial data dump.
```suggestion
                                      Currently the memory footprint is only reduced if bp5 is used, HDF5 and bp4 does not support partial data dump.
```

2024-04-24 10:39 UTC, chillenzer commented on docs/source/usage/plugins/openPMD.rst
> +By using additional to the mapped memory strategy ``--openPMD.particleIOChunkSize N`` you can reduce the memory footprint for particle IO to less than ``2*N`` MiB.
```suggestion
In addition to using the mapped-memory strategy, you can reduce the memory footprint for particle IO to less than ``2*N`` MiB ``--openPMD.particleIOChunkSize N``.
```

2024-04-24 10:39 UTC, chillenzer commented on include/picongpu/plugins/openPMD/WriteSpecies.hpp
> +                uint64_t end)
That is kind of a verbose interface and keeping all three in sync and free of typos will be a hassle. Compared to the C++ evolution of `for`-loop -> iterators and algorithms -> ranges, that's more or less on the `for`-loop level. Not sure if a full abstraction type similar to a range is needed but couldn't one of the three be deduced from the other two?

2024-04-25 07:49 UTC, psychocoderHPC commented on include/picongpu/plugins/openPMD/WriteSpecies.hpp
> +                uint64_t end)
not fully sure what you mean, we should discuss it tomorrow offline. Never the less I will change it and forward `ChunkDescription` which contains all three values in a struct anyway.