fix Gaussian and Dispersive pulse
ComputationalRadiationPhysics/picongpu pull request #4889
Opened 2024-04-26 15:26 UTC by psychocoderHPC

fix #4884

Setting a negative focus was not possible.
This PR projects the PIConGPU coordinates into the laser coordinate system before calculating the distance in laser propagation direction from the laser plane to the current point(cell) we evaluate the pulse.

@finnolec Please check if your issue is solved by this PR.

2024-04-26 15:52 UTC, PrometheusPi requested changes
I am very certain, it will fail under the mentioned condition. I will perform test to validate or disprove my claim.

2024-04-26 15:52 UTC, PrometheusPi commented on include/picongpu/fields/incidentField/profiles/GaussianPulse.hpp
> +                    float_X const focusPos = focusRelativeToOrigin.sumOfComponents() - pos[0];
I am not sure whether this still works if less than 2 of the 3 components are zero.

2024-04-26 15:52 UTC, PrometheusPi commented on include/picongpu/fields/incidentField/profiles/DispersivePulse.hpp
> +                            float_X const focusPos = focusRelativeToOrigin.sumOfComponents() - pos[0];
I am not sure whether this still works if less than 2 of the 3 components are zero.

2024-04-26 15:52 UTC, PrometheusPi commented on include/picongpu/fields/incidentField/profiles/DispersivePulse.hpp
> +                            float_X const focusPos = focusRelativeToOrigin.sumOfComponents() - pos[0];
I am not sure whether this still works if less than 2 of the 3 components are zero.

2024-04-26 16:37 UTC, psychocoderHPC commented
This should not happen because only the orthogonal to the laser plane component should be non zero.

But an additional check is welcome.

Am 26. April 2024 17:52:40 MESZ schrieb Richard Pausch ***@***.***>:
>@PrometheusPi requested changes on this pull request.
>
>I am very certain, it will fail under the mentioned condition. I will perform test to validate or disprove my claim. 
>
>>                      auto const focusRelativeToOrigin = this->focus - this->origin;
> 
>-                    float_X const focusPos = math::sqrt(pmacc::math::l2norm2(focusRelativeToOrigin)) - pos[0];
>+                    // Distance from the current cell to the focus in laser propagation direction.
>+                    float_X const focusPos = focusRelativeToOrigin.sumOfComponents() - pos[0];
>
>I am not sure whether this still works if less than 2 of the 3 components are zero. 
>
>>                              auto const focusRelativeToOrigin = this->focus - this->origin;
>-                            float_X const focusPos = math::sqrt(pmacc::math::l2norm2(focusRelativeToOrigin)) - pos[0];
>+
>+                            // Distance from the current cell to the focus in laser propagation direction.
>+                            float_X const focusPos = focusRelativeToOrigin.sumOfComponents() - pos[0];
>
>I am not sure whether this still works if less than 2 of the 3 components are zero.
>
>
>>                              auto const focusRelativeToOrigin = this->focus - this->origin;
>-                            // current distance to focus position
>-                            float_X const focusPos = math::sqrt(pmacc::math::l2norm2(focusRelativeToOrigin)) - pos[0];
>+
>+                            // Distance from the current cell to the focus in laser propagation direction.
>+                            float_X const focusPos = focusRelativeToOrigin.sumOfComponents() - pos[0];
>
>I am not sure whether this still works if less than 2 of the 3 components are zero.
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ComputationalRadiationPhysics/picongpu/pull/4889#pullrequestreview-2025363981
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

2024-04-29 12:06 UTC, psychocoderHPC commented
@PrometheusPi could you please have a look agin into it, IMO it should now be correct.

2024-05-06 14:58 UTC, PrometheusPi commented
I checked the physics on a non-axis-parallel laser with negative focus position. The pull request fixes the issue. 

In below plots, the focus should be outside the box in, half a box left and up. Thus, curvature should be away from the ficus point. 

The `dev`branch focus to the center:
![grafik](https://github.com/ComputationalRadiationPhysics/picongpu/assets/5121158/223696c4-6796-42a4-a1f1-ba1e428fe517)

The *pull request* fixes that:
![grafik](https://github.com/ComputationalRadiationPhysics/picongpu/assets/5121158/ce6e1cd7-1437-4078-891b-5508dfbbaf9d)

2024-05-06 15:34 UTC, PrometheusPi approved these changes

2024-05-06 15:35 UTC, PrometheusPi commented on include/picongpu/fields/incidentField/profiles/GaussianPulse.hpp
> +                        = pmacc::math::dot(focusRelativeToOrigin, this->getAxis0());
@psychocoderHPC `this->getAxis0()` is a unit vector, right?

2024-05-06 15:58 UTC, merged