Time tracing for the openPMD plugin
ComputationalRadiationPhysics/picongpu pull request #4909
Opened 2024-05-23 15:06 UTC by franzpoeschel

This is something that I've been using for years now on a private branch of PIConGPU, but having an approachable way to get detailed timing information from the openPMD plugin is probably not only relevant for me.

This is disabled by default (via a no-op template specialization), but can be enabled in CMake via `-DPIC_TRACE_OPENPMD_TIMES`. The value of this parameter is an integer that specifies how many MPI ranks should participate in this time tracing. Every MPI rank writes its own output file with timing information, and at large scale only a subselection of MPI ranks should do that in order not to accidentally destroy the performance while trying to measure it.

The output for one run of the plugin may look sth like this:

```
1716472984082   2624    Beginning iteration 50
1716472984135   53      Begin write field E: 25165824 bytes for 2097152 cells 
1716472984135   0               Component 0 prepare
1716472984140   5               Component 0 flush
1716472984153   12              Component 0 end
1716472984153   0               Component 1 prepare
1716472984159   5               Component 1 flush
1716472984171   12              Component 1 end
1716472984171   0               Component 2 prepare
1716472984176   5               Component 2 flush
1716472984189   12              Component 2 end
1716472984192   2       Begin write field B: 25165824 bytes for 2097152 cells 
1716472984192   0               Component 0 prepare
1716472984197   5               Component 0 flush
1716472984209   12              Component 0 end
1716472984209   0               Component 1 prepare
1716472984215   5               Component 1 flush
1716472984227   12              Component 1 end
1716472984227   0               Component 2 prepare
1716472984232   5               Component 2 flush
1716472984244   12              Component 2 end
1716472984244   0       Begin write field e_all_chargeDensity: 8388608 bytes for 2097152 cells
1716472984248   3               Component 0 prepare
1716472984253   4               Component 0 flush
1716472984265   12              Component 0 end
1716472984265   0       Begin write field e_all_energyDensity: 8388608 bytes for 2097152 cells
1716472984268   3               Component 0 prepare
1716472984273   4               Component 0 flush
1716472984285   12              Component 0 end
1716472984285   0       Begin write species e
1716472984315   29              slice 0 prepare: 52428800 bytes for 1310720 particles from offset 0
1716472984346   31              slice 0 flush
1716472984423   76              slice 0 end
1716472984434   11              slice 1 prepare: 52428800 bytes for 1310720 particles from offset 1310720
1716472984465   30              slice 1 flush
1716472984543   78              slice 1 end
1716472984543   0               slice 2 prepare: 0 bytes for 0 particles from offset 2621440
1716472984543   0               slice 2 flush
1716472984676   132             slice 2 end
1716472984676   0               slice 3 prepare: 0 bytes for 0 particles from offset 2621440
1716472984676   0               slice 3 flush
1716472984700   24              slice 3 end
1716472984703   3               Flush species e
1716472984704   0               Finished flush species
1716472984704   0       Closing iteration 50
1716472984840   136     Done.
```
The first column is the UNIX time stamp, the second column the diff time in milliseconds to the previous event, the rest is description.

2024-05-23 15:11 UTC, franzpoeschel reviewed
Some todos for myself

2024-05-23 15:11 UTC, franzpoeschel commented on include/picongpu/CMakeLists.txt
> +set(PIC_TRACE_OPENPMD_TIMES "0" CACHE STRING "Set the maximum number of MPI ranks that create a file with trace information.")
Maybe add something like "NUMBER_OF_FILES" to this option name so people won't think this is a simple boolean

2024-05-23 15:11 UTC, franzpoeschel commented on include/picongpu/plugins/openPMD/DumpTimes.hpp
> +#include <chrono>
Move this file under `plugins/common`

2024-05-23 15:11 UTC, franzpoeschel commented on include/picongpu/plugins/openPMD/DumpTimes.hpp
> +            constexpr static char const* ENV_VAR = "PICONGPU_TIME_TRACE_FILE";
Remove this, it's unused

2024-05-23 15:11 UTC, franzpoeschel commented on include/picongpu/plugins/openPMD/openPMDWriter.def
> +                         * Only up to logs=20 logs should be written in parallel in order not to
This is no longer hardcoded as 20, update comment

2024-05-23 15:11 UTC, franzpoeschel commented on include/picongpu/plugins/openPMD/DumpTimes.hpp
> +        {
In the constructor, write a header with column information to the out file

2024-05-27 10:08 UTC, psychocoderHPC requested changes

2024-05-27 10:08 UTC, psychocoderHPC commented on include/picongpu/CMakeLists.txt
> +set(PIC_IO_TIMES_NUMBER_OF_FILES "0" CACHE STRING "Set the maximum number of MPI ranks that create a file with trace information.")
should be `PIC_OPENPMD_TIMETRACE_NUMBER_OF_FILES`

to reflect that this is only affecting the openpmd plugin and `TIMES` was ambiguous.

2024-05-27 10:08 UTC, psychocoderHPC commented on include/picongpu/CMakeLists.txt
> +add_definitions(-DPIC_IO_TIMES_NUMBER_OF_FILES=${PIC_IO_TIMES_NUMBER_OF_FILES})
please use the changed name for the define too.

2024-05-27 10:08 UTC, psychocoderHPC commented on include/picongpu/plugins/openPMD/openPMDWriter.def
> +            static constexpr bool do_trace_times = PIC_IO_TIMES_NUMBER_OF_FILES > 0;
maybe `timeTraceEnabled` 

note:  we use camel case for variables in PIConGPU

2024-05-27 10:08 UTC, psychocoderHPC commented on include/picongpu/plugins/openPMD/openPMDWriter.def
> +                    constexpr unsigned MAX_LOGS = PIC_IO_TIMES_NUMBER_OF_FILES;
MAX_LOGS -> `maxLogFiles`

2024-05-27 10:08 UTC, psychocoderHPC commented on include/picongpu/plugins/openPMD/openPMDWriter.def
> +                    std::string outputFile = "PIC_times_" + std::to_string(rank) + ".txt";
`PIC_times_` -> `PIC_OpenPMD_TimeTrace` ??

2024-05-27 10:08 UTC, psychocoderHPC commented on include/picongpu/plugins/common/DumpTimes.hpp
> +        template<typename Clock>
` = std::chrono::milliseconds` then we can remove it from a bunch of code but it still allows us to change the precision.

2024-05-27 10:08 UTC, psychocoderHPC commented on include/picongpu/plugins/openPMD/writer/ParticleAttribute.hpp
> +                size_t& accumulate_writtenBytes)
please use camel case naming

2024-05-30 11:39 UTC, franzpoeschel commented on include/picongpu/plugins/openPMD/openPMDWriter.def
> +            static constexpr bool do_trace_times = PIC_IO_TIMES_NUMBER_OF_FILES > 0;
I've used `enableTimeTrace` now

2024-05-30 11:40 UTC, franzpoeschel commented on include/picongpu/plugins/common/DumpTimes.hpp
> +        template<typename Clock>
I've restructured this to:

```cpp
        template<bool enable = true, typename Clock = std::chrono::system_clock>
        class DumpTimes
        {
        public:

            // ...

            using TimeFormatter = typename TimeFormatters<Clock>::TimeFormatter;
```

2024-05-31 08:19 UTC, psychocoderHPC approved these changes

2024-05-31 08:20 UTC, psychocoderHPC approved these changes

2024-05-31 08:20 UTC, merged