refactor `pic-build` and `pic-configure`
ComputationalRadiationPhysics/picongpu pull request #4936
Opened 2024-06-12 10:43 UTC by psychocoderHPC

- expose `-j` parameter for paralell build to the user
- use cmake instead of `make` to call compile and install
- `pic-configure` add parameter `-G` for setting CMake build system

2024-06-12 10:55 UTC, finnolec commented on bin/pic-build
> +    echo "-j [N]                - allow N jobs at once; infinite jobs with no arg"
Maybe we should call it `unlimited jobs` instead of `infinite jobs` like in the `make` documentation? The infinite looks very weird

2024-06-12 12:03 UTC, finnolec commented on bin/pic-build
> +    echo "-j [N]                - allow N jobs at once; infinite jobs with no arg"
Nevermind, this here is 1 to 1 what `make --help` says, I looked at the man-pages.

2024-06-12 12:18 UTC, ikbuibui requested changes

2024-06-12 12:18 UTC, ikbuibui commented on bin/pic-configure
> +    echo "-G <cmakeBuildSystem> - path were picongpu shall be installed"
Documentation is incorrect

2024-06-12 16:20 UTC, psychocoderHPC commented on bin/pic-configure
> +    echo "-G <cmakeBuildSystem> - path were picongpu shall be installed"
updated

2024-06-13 11:51 UTC, ikbuibui approved these changes

2024-06-13 11:52 UTC, merged