Topic add gaussian profile
ComputationalRadiationPhysics/picongpu pull request #4984
Opened 2024-07-08 12:47 UTC by BrianMarre

2024-07-10 07:47 UTC, BrianMarre commented
@steindev ready for review

2024-07-10 09:43 UTC, steindev requested changes

2024-07-10 09:43 UTC, steindev commented on lib/python/picongpu/picmi/distribution/Distribution.py
> +    """Flags whether to fill in the empty spaced opened up when the grid moves"""
spaced -> space

2024-07-10 09:43 UTC, steindev commented on lib/python/picongpu/picmi/distribution/GaussianDistribution.py
> +    """density particle number density, [m^-3]"""
remove first density

2024-07-10 09:43 UTC, steindev commented on lib/python/picongpu/picmi/distribution/GaussianDistribution.py
> +    """center_front center of gaussian ramp at the front, [m]"""
remove `center_front`

2024-07-10 09:43 UTC, steindev commented on lib/python/picongpu/picmi/distribution/GaussianDistribution.py
> +    """center_rear center of the gaussian ramp at the rear, [m]"""
remove `center_rear`

2024-07-10 09:43 UTC, steindev commented on lib/python/picongpu/picmi/distribution/GaussianDistribution.py
> +    """sigma of the gaussian ramp at the front, [m]"""
front -> rear

2024-07-10 09:43 UTC, steindev commented on lib/python/picongpu/pypicongpu/species/operation/densityprofile/gaussian.py
> +    """position of the rear edge of the constant of middle the density profile in meter"""
this is broken

2024-07-10 09:43 UTC, steindev commented on lib/python/picongpu/pypicongpu/species/operation/densityprofile/gaussian.py
> +    """position of the front edge of the constant of middle the density profile in meter"""
also broken

2024-07-10 09:43 UTC, steindev commented on lib/python/picongpu/pypicongpu/species/operation/densityprofile/gaussian.py
> +        density_si * exp(gasFactor * (abs( (y - gasCenterFront) / gasSigmaFront))^gasPower)
density_si -> density, also in the line below

2024-07-10 09:43 UTC, steindev commented on lib/python/picongpu/pypicongpu/species/operation/densityprofile/gaussian.py
> +Authors: Brian Edward Marre, Afshari Masoud
change order of Masoud's names

2024-07-10 09:43 UTC, steindev commented on lib/python/picongpu/pypicongpu/species/operation/densityprofile/gaussian.py
> +    """distance in away from gasCenterFront until the gas density decreases to its 1/e-th part in meter"""
broken

2024-07-10 09:43 UTC, steindev commented on test/python/picongpu/quick/picmi/distribution.py
> +            density=42.42,
Define as global variable (or so) in order to ensure testing against the same values later on.

2024-07-10 09:43 UTC, steindev commented on test/python/picongpu/quick/pypicongpu/species/operation/densityprofile/gaussian.py
> +Copyright 2021-2023 PIConGPU contributors
2024

2024-07-10 09:43 UTC, steindev commented on test/python/picongpu/quick/pypicongpu/species/operation/densityprofile/gaussian.py
> +        """foil is a density profile"""
gaussian?

2024-07-10 09:43 UTC, steindev commented on test/python/picongpu/quick/pypicongpu/species/operation/densityprofile/gaussian.py
> +        """simple scenario works, other plasma ramps are tested separately"""
update?

2024-07-10 09:43 UTC, steindev commented on test/python/picongpu/quick/pypicongpu/species/operation/densityprofile/gaussian.py
> +        g.gas_center_front = 1.0
Define global (or so) variables to ensure testing against equal values.

2024-07-10 09:43 UTC, steindev commented on test/python/picongpu/quick/pypicongpu/species/operation/densityprofile/gaussian.py
> +        g.gas_center_rear = 0.5
put `0.9*gas_center_front`

2024-07-10 09:43 UTC, steindev commented on test/python/picongpu/quick/pypicongpu/species/operation/densityprofile/gaussian.py
> +        g.gas_center_front = 3.0
along the lines of above comment, use 1.1*...

2024-07-10 11:22 UTC, steindev commented
@BrianMarre plkease be aware that this branch currently has conflicts, please resolve these too before your next push.

2024-07-10 16:54 UTC, BrianMarre commented
@steindev ready for review

2024-07-11 15:46 UTC, steindev approved these changes

2024-07-11 15:46 UTC, merged