rename TransitionDataSet to ChooseTransitionGroup
ComputationalRadiationPhysics/picongpu pull request #5065
Opened 2024-08-30 13:24 UTC by BrianMarre

Renames the atomicPhysics enum TransitionDataSet to ChooseTransitionGroup to clearly distinguish between the grouping of transitions used for transition data storage (TransitionType) and the grouping used in the ChooseTransitionType atomicPhysics sub-step.

Also renames the ChooseTransitionType kernal and stage to ChooseTransitionGroup kernel or stage respectively.

2024-09-02 12:53 UTC, steindev commented on include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroup.hpp
> +/** @file chooseTransitionGroup, enum of the groups of transitions macro ions are subdivided into in the
1. "... groups of transitions. Macro ions ..."
2. "into in the"

2024-09-02 12:53 UTC, steindev commented on include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroup.hpp
> + *  ChoosteTransitionTypeKernel
"ChoosteTrans..."

2024-09-02 12:53 UTC, steindev commented on include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroup.hpp
> + *  transition data is organized by transitionType and transitionDirection, see
capital

2024-09-02 12:56 UTC, steindev commented on include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroupFor.hpp
> +        static constexpr ChooseTransitionGroup dataSet = ChooseTransitionGroup::boundBoundUpward;
`dataSet` -> xxx

2024-09-02 13:06 UTC, steindev requested changes
Few typos. See comments above. Otherwise good.

2024-09-02 13:15 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroup.hpp
> +/** @file chooseTransitionGroup, enum of the groups of transitions macro ions are subdivided into in the
fixed

2024-09-02 13:17 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroup.hpp
> + *  ChoosteTransitionTypeKernel
fixed

2024-09-02 13:20 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroup.hpp
> + *  transition data is organized by transitionType and transitionDirection, see
fixed

2024-09-02 13:26 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroupFor.hpp
> +        static constexpr ChooseTransitionGroup dataSet = ChooseTransitionGroup::boundBoundUpward;
renamed to chooseTransitionGroup

2024-09-03 07:52 UTC, PrometheusPi requested changes
looks mostly good - some minor things one might argue about

2024-09-03 07:52 UTC, PrometheusPi commented on docs/source/models/media/AtomicPhyiscsStep_v3_2.svg
deleting and adding new file / moving not really needed of the context of the version number only exists locally but not in the scope of this repo.

2024-09-03 07:52 UTC, PrometheusPi commented on include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroup.hpp
> +            == static_cast<uint8_t>(enums::ChooseTransitionGroup::boundBoundUpward))
why do you not use your `u8`?

2024-09-03 07:52 UTC, PrometheusPi commented on include/picongpu/particles/atomicPhysics/kernel/ChooseTransition_Autonomous.kernel
> +            /// @todo we strictly speaking only need autonomousDownward chooseTransitionGroup, Brian Marre, 2023
typo:
```suggestion
            /// @todo strictly speaking, we only need autonomousDownward chooseTransitionGroup, Brian Marre, 2023
```

2024-09-03 07:59 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroup.hpp
> +            == static_cast<uint8_t>(enums::ChooseTransitionGroup::boundBoundUpward))
I agree it should use the conversion short hand `u8` but this should be a separate PR since it doesn't have anything to do with the renaming.

2024-09-03 08:01 UTC, BrianMarre commented on docs/source/models/media/AtomicPhyiscsStep_v3_2.svg
As discussed offline, I will remove the version number from the FLYonPIC step overview file. This will still cause a rename in this PR but will prevent a similar issue in future PRs.

2024-09-03 08:10 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/kernel/ChooseTransition_Autonomous.kernel
> +            /// @todo we strictly speaking only need autonomousDownward chooseTransitionGroup, Brian Marre, 2023
fixed

2024-09-03 08:58 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroup.hpp
> +            == static_cast<uint8_t>(enums::ChooseTransitionGroup::boundBoundUpward))
switch is implemented in pr #5067

2024-09-03 09:29 UTC, PrometheusPi approved these changes

2024-09-03 18:50 UTC, steindev approved these changes

2024-09-03 18:50 UTC, merged