Topic switch to static cast short hands in atomic physics
ComputationalRadiationPhysics/picongpu pull request #5067
Opened 2024-09-03 08:57 UTC by BrianMarre

This PR requires PR #5065 to be merged first

- replaces static_cast with the atomicPhyiscs short hand functions for better code readability
- marks the short hand functions `u32`, `u8` and `b` as `HDINLINE`

2024-09-04 08:30 UTC, BrianMarre commented
@psychocoderHPC ready for review

2024-09-04 14:42 UTC, psychocoderHPC requested changes

2024-09-04 14:42 UTC, psychocoderHPC commented on include/picongpu/particles/atomicPhysics/ConvertEnum.hpp
> +    HDINLINE constexpr uint8_t u8(T_Enum const enumInstance)
no need to add `HDINLINE`. constexpr is visible on host and device.

I started to remove `HDINLINE constexpr` everywhere in the code

2024-09-05 15:55 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/ConvertEnum.hpp
> +    HDINLINE constexpr uint8_t u8(T_Enum const enumInstance)
done

2024-09-09 10:51 UTC, psychocoderHPC approved these changes

2024-09-09 10:53 UTC, merged