CI: control via commit message
ComputationalRadiationPhysics/picongpu pull request #5074
Opened 2024-09-05 08:25 UTC by psychocoderHPC

- add possibility to control the CI via commit messages
- add basic documentation

This feature is required in case CI tests for PR merges to the dev branch are failing.

2024-09-05 09:46 UTC, psychocoderHPC commented
@ikbuibui PR is ready

2024-09-05 11:04 UTC, ikbuibui requested changes
Some typos and a confusion about unit tests

2024-09-05 11:04 UTC, ikbuibui commented on docs/source/dev/ci.rst
> +There is no guarantee that each setup is compiled with at least on version of the compiles chains above.
```suggestion
There is no guarantee that each setup is compiled with at least one version of the compiler chains above.
```

2024-09-05 11:04 UTC, ikbuibui commented on docs/source/dev/ci.rst
> +It is guaranteed that each compiler version of all compiler chains is compiling at least on PIConGPU input set.
```suggestion
It is guaranteed that each compiler version of all compiler chains is compiling at least one PIConGPU input set.
```

2024-09-05 11:04 UTC, ikbuibui commented on docs/source/dev/ci.rst
> +PIConGPU unit test from ``share/picongpu/unit`` will be compiled and executed  on the corresponding compute device.
```suggestion
PIConGPU unit test from ``share/picongpu/unit`` will be compiled and executed on the corresponding compute device.
```

2024-09-05 11:04 UTC, ikbuibui commented on share/ci/generate_reduced_matrix.sh
> +  if [ $commit_pmacc_only -ne 1 ] ; then
Are these PMacc unit tests or PIConGPU unit tests?
If they are PMacc unit tests, then if condition is wrong and im not sure where the PIConGPU unit tests are added. 
If these are PIConGPU unit tests then the comment below is wrong and im not sure where the PMacc unit tests are (if they exist)

2024-09-05 14:24 UTC, psychocoderHPC commented on share/ci/generate_reduced_matrix.sh
> +  if [ $commit_pmacc_only -ne 1 ] ; then
I fixe the comment, we ahve units test for pmacc, header tests for pmacc and for PIConGPU we ahve unit tests and input set tests.

2024-09-05 14:26 UTC, psychocoderHPC commented
fixed

2024-09-06 07:06 UTC, ikbuibui approved these changes

2024-09-06 07:06 UTC, merged