Switch from mamba to uv
ComputationalRadiationPhysics/picongpu pull request #5082
Opened 2024-09-09 11:38 UTC by chillenzer

#5077 seems to have been insufficient.

2024-09-09 11:52 UTC, psychocoderHPC submitted a review, later dismissed

2024-09-09 14:36 UTC, BrianMarre commented
PyPIConGPU test fail it might have something to do with this setting https://github.com/ComputationalRadiationPhysics/picongpu/blob/89b9640670127075f753c4bc63ec92aa99f5b1d6/.gitlab-ci.yml#L184

2024-09-09 15:15 UTC, psychocoderHPC commented
> PyPIConGPU test fails, might have something to do with this setting
> 
> https://github.com/ComputationalRadiationPhysics/picongpu/blob/89b9640670127075f753c4bc63ec92aa99f5b1d6/.gitlab-ci.yml#L184

@chillenzer I stopped the CI because this must be fixed

2024-09-10 08:17 UTC, chillenzer commented
Thanks for pointing this out. As far as I can see it, the syntax `.*` is not supported by `uv` for selecting a Python version. Pushed an update. Btw, why aren't we on `3.12`?

2024-09-10 08:28 UTC, BrianMarre commented
Because when we built the PyPIConGPU CI Python 3.12 wasn't out yet

2024-09-10 10:37 UTC, psychocoderHPC commented
I stopped the CI again because of errors https://gitlab.com/hzdr/crp/picongpu/-/jobs/7785698774

2024-09-10 10:40 UTC, psychocoderHPC commented
https://github.com/ComputationalRadiationPhysics/picongpu/blob/817b9ebbfec871bf76e8f374a7a974153aeb0663/share/ci/pypicongpu_generator.py#L327

is adding `.*` to the version number

2024-09-10 10:46 UTC, chillenzer commented
Nasty. I have now also run `grep -ri "python" share` and `grep -r '\.\* share` with no further results.

2024-09-10 15:27 UTC, PrometheusPi requested changes
minor comment correction

2024-09-10 15:27 UTC, PrometheusPi commented on share/ci/install/pypicongpu.sh
>  # use miniconda as python environment
comment is now outdated

2024-09-10 15:30 UTC, chillenzer commented on share/ci/install/pypicongpu.sh
>  # use miniconda as python environment
Good catch. I'll remove it once the CI passed such that we can merge without another CI run.

2024-09-10 16:34 UTC, psychocoderHPC commented
It looks like it is not as simple as it sounds to switch the package manager for python.
Let's evaluate if we go on with the switch or stay with micromambda. For now, it looks like IT solved the issues by updating their black list.

2024-09-11 12:19 UTC, chillenzer commented
Apparently, IT has fixed the problem with `mamba` which makes this change unnecessary. Also, we have `snakemake` workflows which would make it particularly inconvenient to leave `mamba` completely. So, we'll close this PR for now.

PS: The failing CI probably just needs a renaming `pip3` -> `[uv ]pip` (not sure if we'd need/want `uv` in front there).

2024-09-11 12:19 UTC, closed without merging

2024-09-11 15:14 UTC, BrianMarre commented
For future reference, Simeon recommended to switch to tox to simplify the PyPIConGPU generator, since tox apparently provides a native way to fix software versions for CI tests.