add atomicPhysicsCI setup
ComputationalRadiationPhysics/picongpu pull request #5129
Opened 2024-09-18 17:17 UTC by BrianMarre

adds the atomic Physics test setup and validation scripts used for runtime tests.

2024-09-18 17:18 UTC, BrianMarre commented
@ikbuibui please add the cfg you are using and maybe a few notes regarding the CI workflow. Thanks!

2024-09-19 10:11 UTC, ikbuibui commented
The way to use the atomic physics test can be simply to copy the test code outside the picongpu source, and execute 
``./validate/validateLocally.sh``

I have added the CFGs I am using for the JUBE CI scaling tests, in folders inside ``etc/`` corresponding to the tests. These CFGs are designed to run on NVIDIA A100 (40 GB) GPUs. The ``single/1.cfg`` is a single GPU test, for the other CFGs the number (eg. ``strong_tiny/4.cfg``) refers to the number of nodes.
One can execute these CFGs with TBG, but validation wont be performed. The user will have to use the custom ``submitAction.sh`` provided with the cfg, or copy the validation folder to the location of the results manually. Finally the user must execute ``validate.sh``. The user should be careful to set the correct CFG and ``submitAction`` paths. 

In the JUBE CI, the workflow is as follows
We call TBG for the scaling test we want to perform (weak/strong, different node sizes). Each scaling test has a set of CFG files associated. JUBE runs the CFGs one by one.
Using a slightly modified ``submitAction.sh``, the TBG call copies over the validation folder to where the results are generated.
In the TPL file, after the ``srun`` to start the simulation, we call the validation script and we are done.

2024-09-19 11:23 UTC, ikbuibui commented
Updated the PR to not hold all the scaling CFGs. Now there are two CFGs in `etc/`, written for use on nodes with 4 NVIDIA A100 (40 GB) GPUs. 
``1.cfg`` holds a single GPU config.
``4.cfg`` holds a 4 node, 4 GPUs per node config.

2024-09-20 09:16 UTC, psychocoderHPC commented
Whats the difference to `tests/compileAtomicPhysics`. If we have an example than the atomic  physics code is already compile test and there is no explicit compile test required.

2024-09-27 09:12 UTC, ikbuibui reviewed
Just comments on the documentation

2024-09-27 09:12 UTC, ikbuibui commented on share/picongpu/examples/AtomicPhysics/README.md
> +This simulation is intended to use the atomic input data files from `https://github.com/ComputationalRadiationPhysics/FLYonPICAtomicTestData`.
Should we link to a private repository?

2024-09-27 09:12 UTC, ikbuibui commented on share/picongpu/examples/AtomicPhysics/README.md
> +If you have access to this repository by `source ./etc/getAtomicInputData.sh` to copy a set of atomic input files to the `atomicInputData`-directory before running the simulation.
```suggestion
If you have access to this repository, execute `./etc/getAtomicInputData.sh` to copy a set of atomic input files to the `atomicInputData`-directory before running the simulation.
```

2024-09-27 09:12 UTC, ikbuibui commented on share/picongpu/examples/AtomicPhysics/README.md
> +Copper ions are initialized cold, no initial momentum, in the ground state, while electrons are given an initial Maxwellian-Temperature of 1 keV.
```suggestion
Copper ions are initialized cold, with no initial momentum, in the ground state, while electrons are given an initial Maxwellian-Temperature of 1 keV.
```

2024-09-27 09:12 UTC, ikbuibui commented on share/picongpu/examples/AtomicPhysics/README.md
> +2.) run `source ./validate/validateLocally.sh` to validate the simulation results
```suggestion
2.) run `./validate/validateLocally.sh` to validate the simulation results
```
Shouldn't source unless required

2024-09-27 09:12 UTC, ikbuibui commented on share/picongpu/examples/AtomicPhysics/README.md
> +2.) provide the atomic input data using `source ./etc/getAtomicInputData.sh`, requires access to the test setup.
```suggestion
2.) provide the atomic input data using `./etc/getAtomicInputData.sh`, requires access to the test setup.
```
Shouldn't source unless required

2024-09-27 09:12 UTC, ikbuibui commented on share/picongpu/examples/AtomicPhysics/README.md
> +The setup comes with `.cfg`-files designed to run on NVIDIA A100 (40 GB) GPU nodes from the JUBE CI.
```suggestion
The setup comes with `.cfg`-files designed to run on NVIDIA A100 (40 GB) GPU nodes from JURECA using the JUBE CI.
```

2024-09-27 10:28 UTC, BrianMarre commented on share/picongpu/examples/AtomicPhysics/README.md
> +This simulation is intended to use the atomic input data files from `https://github.com/ComputationalRadiationPhysics/FLYonPICAtomicTestData`.
Well so long as it is private the URL will not resolve unless the user has logged in and the user is authorized.
And it's the easiest way to distribute the input files to users.

2024-09-27 10:29 UTC, BrianMarre commented on share/picongpu/examples/AtomicPhysics/README.md
> +If you have access to this repository by `source ./etc/getAtomicInputData.sh` to copy a set of atomic input files to the `atomicInputData`-directory before running the simulation.
done

2024-09-27 10:30 UTC, BrianMarre commented on share/picongpu/examples/AtomicPhysics/README.md
> +Copper ions are initialized cold, no initial momentum, in the ground state, while electrons are given an initial Maxwellian-Temperature of 1 keV.
done

2024-09-27 10:30 UTC, BrianMarre commented on share/picongpu/examples/AtomicPhysics/README.md
> +2.) run `source ./validate/validateLocally.sh` to validate the simulation results
done

2024-09-27 10:30 UTC, BrianMarre commented on share/picongpu/examples/AtomicPhysics/README.md
> +2.) provide the atomic input data using `source ./etc/getAtomicInputData.sh`, requires access to the test setup.
done

2024-09-27 10:31 UTC, BrianMarre commented on share/picongpu/examples/AtomicPhysics/README.md
> +The setup comes with `.cfg`-files designed to run on NVIDIA A100 (40 GB) GPU nodes from the JUBE CI.
done

2024-09-30 07:46 UTC, ikbuibui approved these changes, later dismissed

2024-09-30 08:40 UTC, psychocoderHPC requested changes

2024-09-30 08:40 UTC, psychocoderHPC commented on share/picongpu/examples/AtomicPhysics/include/picongpu/param/speciesDefinition.param
> +#include "picongpu/simulation_defines.hpp"
this wile dows not exits anymore and it would be also wrong to include this within a param file

2024-10-01 07:33 UTC, psychocoderHPC approved these changes

2024-10-01 07:34 UTC, merged