Re-add NoIPD
ComputationalRadiationPhysics/picongpu pull request #5152
Opened 2024-10-02 10:41 UTC by BrianMarre

re-add the NoIPD implementation of FLYonPIC removed in PR #5147

- [ ] requires PR #5147 to be merged first
- [ ] must be rebased once PR # 5147 has been merged

2024-10-02 14:26 UTC, BrianMarre commented
@psychocoderHPC ready for review

2024-10-08 14:33 UTC, chillenzer approved these changes

2024-10-09 08:59 UTC, psychocoderHPC requested changes

2024-10-09 08:59 UTC, psychocoderHPC commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/NoIPD.hpp
> +#include "picongpu/particles/atomicPhysics/ionizationPotentialDepression/IPDModel.hpp"
please remove this include, it is not required.

2024-10-09 08:59 UTC, psychocoderHPC approved these changes

2024-10-09 08:59 UTC, merged