bugFix calculate IPD input
ComputationalRadiationPhysics/picongpu pull request #5204
Opened 2024-11-07 15:00 UTC by BrianMarre

Fixes two bug in the calculation of the debye length in atomicPhysics(FLYonPIC) for the StewartPyatt IPD Model.

I mistakenly used the cell volume instead of the SuperCellVolume and forgot a conversion factor for `k_B * T`.

2024-11-08 09:49 UTC, chillenzer requested changes, later dismissed
Offline discussion: I'm a rubber duck and @BrianMarre found something that's still wrong.

2024-11-08 10:28 UTC, BrianMarre commented
@chillenzer fixed

2024-11-11 08:01 UTC, psychocoderHPC requested changes

2024-11-11 08:01 UTC, psychocoderHPC commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
> +            float_X& temperatureEnergy = temperatureEnergyBox(superCellFieldIdx);
please use `float_X` and not `float_X&` this leads very fast to invalid memory access especially if the right-hand side returns a temporary.
This will also not good from the point of performance.

2024-11-11 08:01 UTC, psychocoderHPC commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
> +            float_X& temperatureEnergy = temperatureEnergyBox(superCellFieldIdx);
Please fix the next 2 lines too.

2024-11-11 08:01 UTC, psychocoderHPC commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
>              //}
please remove `//}` this has no meening if you would use doxygen grouping than use `/** @{ */` and ` /** @} */` please

2024-11-11 08:01 UTC, psychocoderHPC commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
>              //{
please remove `//}` this has no meening if you would use doxygen grouping than use `/** @{ */` and ` /** @} */` please

2024-11-11 08:01 UTC, psychocoderHPC commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
> +                    // (unitless * weight / sim.unit.typicalNumParticlesPerMacroParticle())
The comment looks like you discribe `X/X == 1`

2024-11-11 08:01 UTC, psychocoderHPC commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
> +                    // k_Boltzman * Temperature, energy equivalent to the local temperature
This comment should be merged with the comment (dead code) above. If you like to have a separation please use an empty line.

2024-11-11 08:01 UTC, psychocoderHPC commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
> +                    // sim.unit.length()^3
join with comment above. All comment above are for the next line

2024-11-11 09:50 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
> +            float_X& temperatureEnergy = temperatureEnergyBox(superCellFieldIdx);
done

2024-11-11 09:52 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
>              //}
done

2024-11-11 09:52 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
>              //{
done

2024-11-11 10:01 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
> +                    // sim.unit.length()^3
done

2024-11-11 10:01 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
> +                    // k_Boltzman * Temperature, energy equivalent to the local temperature
done

2024-11-11 10:02 UTC, BrianMarre commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
> +                    // (unitless * weight / sim.unit.typicalNumParticlesPerMacroParticle())
No I am describing the unit of the result of the calculation

2024-11-12 11:37 UTC, psychocoderHPC approved these changes

2024-11-12 11:37 UTC, psychocoderHPC commented on include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/StewartPyattIPD.hpp
> +            // eV/(sim.unit.energy())
note: should be `unit_enegy` -> not nessary only  an info

2024-11-12 11:37 UTC, merged