Add picmi_schema
ComputationalRadiationPhysics/picongpu pull request #5232
Opened 2024-12-11 16:24 UTC by mafshari64

Add picmi_schema for picmi input files.

2024-12-12 12:37 UTC, psychocoderHPC commented
Does PICMI somehow use this schema or is this an independent file. 
How do we ensure that PICME is following the schema.

2024-12-12 12:41 UTC, mafshari64 commented
this schema in principle should check if the input file created based on the PICMI standard follows its role, eg units are correct.

2024-12-13 08:58 UTC, psychocoderHPC commented
But how is the PICMI file checked against the schema, I do not see an integration into the PICMI python code.

2024-12-13 12:22 UTC, BrianMarre commented
Some general remarks:
- the name of this schema is misleading since this schema has nothing to do with PICMI,

rather it describes the structure of the PyPIConGPU json description of an picongpu setup assumed by the meta data exporter, therefore it belongs to the meta data exporter and should use it's own project name to avoid confusion with the PyPIConGPU schemas.

- this schema is mostly a repeat of the PyPIConGPU schemas, which already specify the structure of the PyPIConGPU json description.
- this schema has nothing to do with PIConGPU and belongs to the meta data exporter project, since it describes assumptions/requirements of the meta data exporter not PIConGPU, PyPIConGPU or the PIConGPU PICMI implementation.

2024-12-13 12:23 UTC, BrianMarre requested changes
Some general remarks:
- the name of this schema is misleading since this schema has nothing to do with PICMI,

rather it describes the structure of the PyPIConGPU json description of an picongpu setup assumed by the meta data exporter, therefore it belongs to the meta data exporter and should use it's own project name to avoid confusion with the PyPIConGPU schemas.

- this schema is mostly a repeat of the PyPIConGPU schemas, which already specify the structure of the PyPIConGPU json description.
- this schema has nothing to do with PIConGPU and belongs to the meta data exporter project, since it describes assumptions/requirements of the meta data exporter not PIConGPU, PyPIConGPU or the PIConGPU PICMI implementation.

2025-02-10 13:53 UTC, chillenzer requested changes
_Offline discussion:_ These are the notes taken during our offline discussion.

2025-02-10 13:53 UTC, chillenzer commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +    phase_space_species_name = util.build_typesafe_property(str)
Pass this as species object and not just by name.

2025-02-10 13:53 UTC, chillenzer commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +    phase_space_space = util.build_typesafe_property(str)
Means spatial dimension/component/axis/... better use enum to represent this.

2025-02-10 13:53 UTC, chillenzer commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +    phase_space_momentum = util.build_typesafe_property(str)
Same as `space`

2025-02-10 13:53 UTC, chillenzer commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +    phase_space_max = util.build_typesafe_property(float)
Look up what these actually constrain and use a more descriptive name.
Also, don't we need at least four of them?

2025-02-10 13:53 UTC, chillenzer commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +    phase_space_filter = util.build_typesafe_property(str)
Use an object again.

2025-02-10 13:53 UTC, chillenzer commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +        }
Serialise full objects and refer to the objects for doing so. (Filling in the template will later select the data that are actually needed.)

2025-02-10 13:53 UTC, chillenzer commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +        }
See https://github.com/mafshari64/picongpu/blob/38365e974b1ca55a34d718df94ab051334e380f3/lib/python/picongpu/pypicongpu/species/operation/simpledensity.py#L123 for an example.

2025-02-10 13:53 UTC, chillenzer commented on share/picongpu/pypicongpu/schema/output/phase_space.json
Update according to the updates in `phase_space.py`. Example: Refer to an existing schema for species.

2025-02-10 13:53 UTC, chillenzer commented on share/picongpu/pypicongpu/schema/output/phase_space.json
https://github.com/mafshari64/picongpu/blob/38365e974b1ca55a34d718df94ab051334e380f3/share/picongpu/pypicongpu/schema/simulation.Simulation.json#L32C21-L32C27

2025-02-10 13:53 UTC, chillenzer commented on share/picongpu/pypicongpu/schema/output/phase_space.json
> +    "required": ["phase_space_species_name", "phase_space_period", "phase_space_space", "phase_space_momentum"],
Should contain all of the below.

2025-02-10 13:53 UTC, chillenzer commented on share/picongpu/pypicongpu/schema/output/phase_space.json
> +            "type": "string",
Example: https://github.com/mafshari64/picongpu/blob/38365e974b1ca55a34d718df94ab051334e380f3/share/picongpu/pypicongpu/schema/simulation.Simulation.json#L56

2025-02-14 16:15 UTC, mafshari64 commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +    phase_space_species_name = util.build_typesafe_property(str)
Done

2025-02-18 09:46 UTC, mafshari64 commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +    phase_space_space = util.build_typesafe_property(str)
done

2025-02-18 09:46 UTC, mafshari64 commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +    phase_space_momentum = util.build_typesafe_property(str)
done

2025-02-18 09:46 UTC, mafshari64 commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +    phase_space_max = util.build_typesafe_property(float)
done

2025-02-18 09:46 UTC, mafshari64 commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +    phase_space_filter = util.build_typesafe_property(str)
done

2025-02-18 09:52 UTC, mafshari64 commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +        }
done

2025-02-18 09:52 UTC, mafshari64 commented on lib/python/picongpu/pypicongpu/output/phase_space.py
> +    phase_space_filter = util.build_typesafe_property(str)
done

2025-02-18 09:52 UTC, mafshari64 commented on share/picongpu/pypicongpu/schema/output/phase_space.json
done

2025-02-18 09:52 UTC, mafshari64 commented on share/picongpu/pypicongpu/schema/output/phase_space.json
> +    "required": ["phase_space_species_name", "phase_space_period", "phase_space_space", "phase_space_momentum"],
done

2025-02-18 09:52 UTC, mafshari64 commented on share/picongpu/pypicongpu/schema/output/phase_space.json
> +            "type": "string",
done

2025-04-28 11:48 UTC, PrometheusPi commented
@mafshari64 @chillenzer what's the status of this PR?

2025-05-05 08:34 UTC, chillenzer commented
As of now, this belongs to a separate project and bears no functionality within the code base of this code. If, at one point, a mature web interface exists, we might reconsider merging the whole interface which would include this file but not this file individually. Currently, we have no means to test this or keep this up to date, so we can't afford having this in our repository.

2025-05-05 08:34 UTC, closed without merging