update memory calculator
ComputationalRadiationPhysics/picongpu pull request #5244
Opened 2024-12-19 19:11 UTC by BrianMarre

This PR,
- refactors the memory calculator:
  - type validation using pydantic
  - function signature checks using typeguard
  - remove explicit passing of extents by dimension
  - changes particle attribute specification to be by list of names
  - updates the pml border default size to the current defaults
  - changes the pml border size specification to match the param files
- refactors the use example
  - bug-fix in the particle memory calculation, now uses sim dimension 2 instead of the old default value 3
  - update to the new interfaces
  - generalize the implementation
  - switches to per gpu output instead of per row output
- adds the memory calculation for atomic physics super cell fields and atomic physics particle attributes

2024-12-20 10:23 UTC, pordyna requested changes
Nice! Looks mostly good to me, though I made some mostly just pedantic comments.

2024-12-20 10:23 UTC, pordyna commented on docs/source/usage/workflows/memoryPerDevice.py
> +print(f"global domain division: {global_domain_division}")
For me, it is not clear what domain division is supposed to be. I think you should name it differently.

2024-12-20 10:23 UTC, pordyna commented on docs/source/usage/workflows/memoryPerDevice.py
> +# get cell extent of each GPU, <extent of the gpu domain>[simulation dimension, multi dimensional gpu index]
Not sure I get this notation

2024-12-20 10:23 UTC, pordyna commented on docs/source/usage/workflows/memoryPerDevice.py
> +        # fully in side target
```suggestion
        # fully inside target
```

2024-12-20 10:23 UTC, pordyna commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +    def get_predefined_attribute_dict(simulation_dimension: int, precision: int) -> dict[str, int]:
Why is it a static method? `simulation_dimension`, `precision` are also instance attributes. So as long as you put in the class, I would make just use these values.

2024-12-20 10:23 UTC, pordyna commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +    def check_cell_extent(self, cell_extent: nptype.NDArray):
Not part of the user interface. I think you should hide it by prepending `_` to the method name.

2024-12-20 10:23 UTC, pordyna commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +    def checkDimensionsOfArrays(self):
Also, not part of the user interface. I think you should hide it by prepending `_` to the method name.

2024-12-20 10:23 UTC, pordyna commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +    def shrink_to_simulation_dimension(self):
Also, not part of the user interface. I think you should hide it by prepending `_` to the method name.

2024-12-20 10:23 UTC, pordyna commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +    def check(self):
Also, not part of the user interface. I think you should hide it by prepending `_` to the method name.

2024-12-20 10:23 UTC, pordyna commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        # one scalar each for temp fields, E_x, B_x, E_y, B_y, ...
```suggestion
        # one scalar for each temp field, E, B, and J field component
```

2024-12-20 10:23 UTC, pordyna commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        IPDactive: bool = True,
`IPDactive` -> `ipd_active`

2024-12-20 13:34 UTC, BrianMarre commented on docs/source/usage/workflows/memoryPerDevice.py
> +print(f"global domain division: {global_domain_division}")
after an offline discussion I followed Pawel's advice and renamed it to ``grid_distribution`` to match more closely the PIConGPU terminology.

2024-12-20 13:38 UTC, BrianMarre commented on docs/source/usage/workflows/memoryPerDevice.py
> +# get cell extent of each GPU, <extent of the gpu domain>[simulation dimension, multi dimensional gpu index]
rephrased the comment to make it clearer.

2024-12-20 13:38 UTC, BrianMarre commented on docs/source/usage/workflows/memoryPerDevice.py
> +        # fully in side target
fixed

2024-12-20 13:39 UTC, BrianMarre commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +    def get_predefined_attribute_dict(simulation_dimension: int, precision: int) -> dict[str, int]:
since these methods might be usable in other contexts I decided to make them independent of the current implementation.

2024-12-20 13:40 UTC, BrianMarre commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +    def check_cell_extent(self, cell_extent: nptype.NDArray):
fixed

2024-12-20 13:41 UTC, BrianMarre commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +    def checkDimensionsOfArrays(self):
fixed

2024-12-20 13:41 UTC, BrianMarre commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +    def shrink_to_simulation_dimension(self):
fixed

2024-12-20 13:42 UTC, BrianMarre commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +    def check(self):
fixed

2024-12-20 13:43 UTC, BrianMarre commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        # one scalar each for temp fields, E_x, B_x, E_y, B_y, ...
fixed

2024-12-20 13:46 UTC, BrianMarre commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        IPDactive: bool = True,
fixed

2025-01-06 10:29 UTC, pordyna commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +    def get_predefined_attribute_dict(simulation_dimension: int, precision: int) -> dict[str, int]:
@BrianMarre ok, but in that case I would just take it out of the class :)

2025-01-08 14:41 UTC, chillenzer requested changes
I have strong opinions about the qualities of my bike's accommodation but there's actually one thing about the counting in bits and bytes that needs reworking. Others are optional. Haven't checked if the details of the memory usage actually match up with what the code does.

2025-01-08 14:41 UTC, chillenzer commented on docs/source/usage/workflows/memoryPerDevice.py
[This line](https://github.com/ComputationalRadiationPhysics/picongpu/blob/79ee6eff1ff0ec8240db75171251bc1a1fa2977d/docs/source/usage/workflows/memoryPerDevice.rst?plain=1#L26) needs adaption. See the wrong rendering of the example code [here](https://picongpu--5244.org.readthedocs.build/en/5244/usage/workflows/memoryPerDevice.html).

2025-01-08 14:41 UTC, chillenzer commented on docs/source/usage/workflows/memoryPerDevice.py
>  equally in transverse direction, like it is set up in the FoilLCT example.
While we're at it, this is a duplication of the text in [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/79ee6eff1ff0ec8240db75171251bc1a1fa2977d/docs/source/usage/workflows/memoryPerDevice.rst?plain=1#L13). I would suggest to to deduplicate by using another literal include in the rst version. Maybe something like "The following script's docstring explains its functionality: ... (<literal include here>)

2025-01-08 14:41 UTC, chillenzer commented on docs/source/usage/workflows/memoryPerDevice.py
> +gpu_cell_extent = np.meshgrid(*grid_distribution)
```suggestion
gpu_cell_extent = (global_cell_extent / global_gpu_extent * np.ones([simulation_dimension, *global_gpu_extent])).astype(int).T
```
Equivalent oneliner (up to the fact that we're getting a numpy array, of course). I was tempted to use an explicit `np.floor` to hint on the fact that we're potentially cutting something off here. But the `ValueError` above takes care of this. We might want to print the `gpu_cell_extent` instead of the `grid_distribution` in this case.

2025-01-08 14:41 UTC, chillenzer commented on docs/source/usage/workflows/memoryPerDevice.py
> +
Maybe a more explicit warning would be nice here: Something along the lines of "... and there are scenarios (e.g. imploding setups) where the not-moving approximation severely underestimates memory requirements of individual GPUs. So take it with a grain of salt as an order-of-magnitude estimate."

2025-01-08 14:41 UTC, chillenzer commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        }
Offline discussion: Use bytes and bools are (undefined but typically) larger than 1 bit. Technically, a byte could have a different size than 8.

2025-01-08 14:41 UTC, chillenzer commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        number_local_cells = int(np.prod(cell_extent + self.super_cell_size * 2 * self.guard_size))
It's not quite obvious what `cell_extent` refers to. It looks like it means `extent_in_number_of_cells` while I first read it as `extent_of_a_cell`. Better name would be great.

2025-01-08 14:41 UTC, chillenzer commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        @return unit: bytes
Offline discussion: Remove default ppc and number of particles directly needs ppc=1

2025-01-08 14:41 UTC, chillenzer commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        @param cell_extent device cell extent
Just to distinguish from below: Be explicit that a volume (a number) is not sufficient, we need a vector here.

2025-01-08 14:43 UTC, chillenzer commented
Forgot: Offline discussion in the meeting: We want to keep the main example minimal and concrete (and not have the "kind of general" computation for varying parameters) and might add the "how to compute the used values" in a separate section.

2025-01-08 15:11 UTC, BrianMarre commented on docs/source/usage/workflows/memoryPerDevice.py
fixed, also left a not for future developers

2025-01-08 15:12 UTC, BrianMarre commented on docs/source/usage/workflows/memoryPerDevice.py
fixed

2025-01-08 15:26 UTC, BrianMarre commented on docs/source/usage/workflows/memoryPerDevice.py
>  equally in transverse direction, like it is set up in the FoilLCT example.
not my fault, but I fixed it anyway

2025-01-08 15:45 UTC, BrianMarre commented on docs/source/usage/workflows/memoryPerDevice.py
> +
done.

2025-01-08 15:57 UTC, BrianMarre commented on docs/source/usage/workflows/memoryPerDevice.py
> +gpu_cell_extent = np.meshgrid(*grid_distribution)
as discussed offline, we decided to hard code values, for better redability.

2025-01-08 18:20 UTC, BrianMarre commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        }
done

2025-01-08 18:21 UTC, BrianMarre commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        @return unit: bytes
done

2025-01-08 18:23 UTC, BrianMarre commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        @param cell_extent device cell extent
done

2025-01-08 18:23 UTC, BrianMarre commented
> Forgot: Offline discussion in the meeting: We want to keep the main example minimal and concrete (and not have the "kind of general" computation for varying parameters) and might add the "how to compute the used values" in a separate section.
done

2025-01-09 10:02 UTC, BrianMarre commented on lib/python/picongpu/extra/utils/memory_calculator.py
> +        number_local_cells = int(np.prod(cell_extent + self.super_cell_size * 2 * self.guard_size))
It is supposed the describe the extent of the spatial domain of a GPU in cells, I failed not come up with a better name so would keep it for now and let the next person figure out a better name.

2025-01-09 11:58 UTC, chillenzer approved these changes

2025-01-09 12:00 UTC, merged